// AUTO-GENERATED by tools/generate_enterprise_sdks.py
using System.Net;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace SafeRx;

public sealed record EnterpriseOperation(string OperationId, HttpMethod Method, string Path, bool IdempotencyRequired);

public sealed class SafeRxProblemDetailsException : Exception
{
    public HttpStatusCode StatusCode { get; }
    public JsonElement Problem { get; }
    public SafeRxProblemDetailsException(HttpStatusCode statusCode, JsonElement problem) : base(problem.ValueKind == JsonValueKind.Object && problem.TryGetProperty("detail", out var detail) ? detail.GetString() : "Enterprise request failed") { StatusCode = statusCode; Problem = problem; }
}

public sealed class SafeRxClient
{
    public const string SdkVersion = "2.0.2-preview.1";
    public static readonly IReadOnlyDictionary<string, EnterpriseOperation> Operations = new Dictionary<string, EnterpriseOperation>
    {
        ["enterprise_erx_safety_check"] = new EnterpriseOperation("enterprise_erx_safety_check", HttpMethod.Post, "/erx/safety-checks", true),
        ["enterprise_ocr_prescription_create"] = new EnterpriseOperation("enterprise_ocr_prescription_create", HttpMethod.Post, "/ocr/prescriptions", true),
        ["enterprise_ocr_prescription_events"] = new EnterpriseOperation("enterprise_ocr_prescription_events", HttpMethod.Get, "/ocr/prescriptions/{prescription_id}/events", false),
        ["enterprise_ocr_prescription_read"] = new EnterpriseOperation("enterprise_ocr_prescription_read", HttpMethod.Get, "/ocr/prescriptions/{prescription_id}", false),
        ["enterprise_ocr_prescription_resolve"] = new EnterpriseOperation("enterprise_ocr_prescription_resolve", HttpMethod.Post, "/ocr/prescriptions/{prescription_id}/medications/resolve", false),
        ["enterprise_ocr_prescription_review"] = new EnterpriseOperation("enterprise_ocr_prescription_review", HttpMethod.Post, "/ocr/prescriptions/{prescription_id}/review", false),
        ["enterprise_ocr_prescription_safety"] = new EnterpriseOperation("enterprise_ocr_prescription_safety", HttpMethod.Post, "/ocr/prescriptions/{prescription_id}/safety-checks", false),
        ["enterprise_registry_autocomplete"] = new EnterpriseOperation("enterprise_registry_autocomplete", HttpMethod.Get, "/registry/suggest", false),
        ["enterprise_registry_ingredients"] = new EnterpriseOperation("enterprise_registry_ingredients", HttpMethod.Get, "/registry/ingredients", false),
        ["enterprise_registry_product_detail"] = new EnterpriseOperation("enterprise_registry_product_detail", HttpMethod.Get, "/registry/products/{sfrx_id}", false),
        ["enterprise_registry_resolve"] = new EnterpriseOperation("enterprise_registry_resolve", HttpMethod.Post, "/registry/resolve", false),
        ["enterprise_registry_search"] = new EnterpriseOperation("enterprise_registry_search", HttpMethod.Get, "/registry/search", false),
        ["enterprise_safety_capabilities"] = new EnterpriseOperation("enterprise_safety_capabilities", HttpMethod.Get, "/safety/capabilities", false),
        ["enterprise_safety_check"] = new EnterpriseOperation("enterprise_safety_check", HttpMethod.Post, "/safety/checks", true),
    };
    private const int MaxAttempts = 3;
    private const double RetryBackoffBaseSeconds = 0.1;
    private const double RetryBackoffMaxSeconds = 2.0;
    private const double RetryAfterMaxSeconds = 60.0;
    private readonly HttpClient _http; private readonly Uri _baseUrl; private readonly string _apiKey; private readonly string _clientName;
    public SafeRxClient(HttpClient http, Uri baseUrl, string apiKey, string clientName = "SafeRx") { _http = http; _baseUrl = baseUrl; _apiKey = apiKey; _clientName = clientName; }

    private static double RetryDelaySeconds(RetryConditionHeaderValue? retryAfter, int attempt)
    {
        var backoff = Math.Min(RetryBackoffMaxSeconds, RetryBackoffBaseSeconds * Math.Pow(2, attempt));
        if (retryAfter?.Delta is TimeSpan delta) return Math.Min(RetryAfterMaxSeconds, Math.Max(backoff, delta.TotalSeconds));
        if (retryAfter?.Date is DateTimeOffset date) return Math.Min(RetryAfterMaxSeconds, Math.Max(backoff, (date - DateTimeOffset.UtcNow).TotalSeconds));
        return backoff;
    }

    public async Task<JsonElement> RequestAsync(string operationId, object? body = null, IReadOnlyDictionary<string, string>? pathParams = null, string? idempotencyKey = null, CancellationToken cancellationToken = default)
    {
        if (!Operations.TryGetValue(operationId, out var operation)) throw new ArgumentException("Unknown Enterprise operation", nameof(operationId));
        var path = operation.Path; foreach (var pair in pathParams ?? new Dictionary<string, string>()) path = path.Replace("{" + pair.Key + "}", Uri.EscapeDataString(pair.Value), StringComparison.Ordinal);
        if (operation.IdempotencyRequired && string.IsNullOrWhiteSpace(idempotencyKey)) throw new ArgumentException("Operation requires idempotencyKey", nameof(idempotencyKey));
        var json = body is null ? "" : JsonSerializer.Serialize(body, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase }); var bytes = Encoding.UTF8.GetBytes(json);
        var requestId = Guid.NewGuid().ToString();
        var bodyHash = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
        for (var attempt = 0; attempt < MaxAttempts; attempt++) {
            var timestamp = DateTimeOffset.UtcNow.ToString("O"); var nonce = Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant();
            var signingPath = _baseUrl.AbsolutePath.TrimEnd('/') + path;
            var canonical = string.Join("\n", operation.Method.Method.ToUpperInvariant(), signingPath, "", bodyHash, timestamp, nonce);
            using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(_apiKey)); var signature = Convert.ToBase64String(hmac.ComputeHash(Encoding.UTF8.GetBytes(canonical))).TrimEnd('=').Replace('+', '-').Replace('/', '_');
            var requestUri = new Uri(new Uri(_baseUrl.ToString().TrimEnd('/') + "/"), path.TrimStart('/'));
            using var request = new HttpRequestMessage(operation.Method, requestUri); request.Headers.TryAddWithoutValidation("X-SafeRx-API-Key", _apiKey); request.Headers.TryAddWithoutValidation("X-SafeRx-Timestamp", timestamp); request.Headers.TryAddWithoutValidation("X-SafeRx-Nonce", nonce); request.Headers.TryAddWithoutValidation("X-SafeRx-Signature", signature); request.Headers.TryAddWithoutValidation("X-Request-ID", requestId); request.Headers.TryAddWithoutValidation("X-SafeRx-Client-Kind", "csharp_sdk"); request.Headers.TryAddWithoutValidation("X-SafeRx-Client-Name", _clientName); request.Headers.TryAddWithoutValidation("X-SafeRx-Client-Version", SdkVersion); request.Headers.TryAddWithoutValidation("X-SafeRx-SDK-Language", "csharp"); request.Headers.TryAddWithoutValidation("X-SafeRx-SDK-Version", SdkVersion); if (idempotencyKey is not null) request.Headers.TryAddWithoutValidation("Idempotency-Key", idempotencyKey); if (body is not null) request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            try { using var response = await _http.SendAsync(request, cancellationToken); var raw = await response.Content.ReadAsStringAsync(cancellationToken); var parsed = JsonSerializer.Deserialize<JsonElement>(string.IsNullOrWhiteSpace(raw) ? "null" : raw); if (response.IsSuccessStatusCode) return parsed; if (!new[] { 429, 502, 503, 504 }.Contains((int)response.StatusCode) || attempt + 1 >= MaxAttempts) throw new SafeRxProblemDetailsException(response.StatusCode, parsed); await Task.Delay(TimeSpan.FromSeconds(RetryDelaySeconds(response.Headers.RetryAfter, attempt)), cancellationToken); } catch (SafeRxProblemDetailsException) { throw; } catch (HttpRequestException) when (attempt + 1 < MaxAttempts) { await Task.Delay(TimeSpan.FromSeconds(Math.Min(RetryBackoffMaxSeconds, RetryBackoffBaseSeconds * Math.Pow(2, attempt))), cancellationToken); }
        }
        throw new InvalidOperationException("retry loop exhausted");
    }
}
