// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../../../../index.js";

/**
 * @example
 *     {
 *         drugs: ["Augmentin 1g", "Glucophage 500mg", "Marivan"],
 *         lang: "en"
 *     }
 *
 * @example
 *     {
 *         drugs: ["Augmentin 1g", "Glucophage 500mg", "Marivan"],
 *         patient_profile: {
 *             populations: ["geriatric", "renal"],
 *             conditions: ["diabetes", "hypertension"]
 *         },
 *         include: ["ae", "ddi", "pllr", "clinical"],
 *         lang: "en"
 *     }
 *
 * @example
 *     {
 *         drugs: ["Augmentin 1g", "Marivan"],
 *         include: ["ddi"]
 *     }
 *
 * @example
 *     {
 *         drugs: ["Augmentin 1g", "Glucophage 500mg"],
 *         lang: "ar"
 *     }
 */
export interface DrugSafetyCheckRequest {
    /**
     * Drug names to screen. Accepts trade names (e.g., "Augmentin 1g"),
     * generic names (e.g., "amoxicillin"), or partial matches.
     * Fuzzy matching resolves names to SafeRx product IDs.
     *
     * - **Free/Pro tier:** max 20 drugs per request
     * - **Enterprise tier:** max 50 drugs per request
     */
    drugs: string[];
    patient_profile?: SafeRx.PatientProfile;
    /**
     * Safety domains to check. Omit to run all six domains.
     * Including fewer domains reduces response size and may improve latency.
     */
    include?: SafeRx.DomainCode[];
    /**
     * Response language. Controls bilingual fields such as rationale text,
     * drug name translations, and clinical advice.
     */
    lang?: DrugSafetyCheckRequest.Lang;
}

export namespace DrugSafetyCheckRequest {
    /**
     * Response language. Controls bilingual fields such as rationale text,
     * drug name translations, and clinical advice.
     */
    export const Lang = {
        En: "en",
        Ar: "ar",
    } as const;
    export type Lang = (typeof Lang)[keyof typeof Lang];
}
