# This file was auto-generated by Fern from our API Definition.

import typing

AlertType = typing.Union[
    typing.Literal["ae_bbw", "ddi", "pllr_pregnancy", "pllr_lactation", "clinical_condition", "clinical_population"],
    typing.Any,
]
