# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BlackBoxWarning(UniversalBaseModel):
    warning_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full BBW text in English
    """

    warning_text_ar: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full BBW text in Arabic
    """

    categories: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    BBW category tags (e.g., DEATH_RISK, BLEEDING_RISK, CARDIAC_RISK,
    HEPATOTOXICITY, SUICIDALITY, TERATOGENIC)
    """

    has_death_warning: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this BBW includes a mortality risk
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source of the BBW data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
