# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ClinicalAlertSpecialNotes(UniversalBaseModel):
    """
    Additional clinical notes
    """

    geriatric_high_risk: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this drug is flagged as high-risk for elderly patients
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
