# This file was auto-generated by Fern from our API Definition.

import typing

Condition = typing.Union[
    typing.Literal[
        "arrhythmia",
        "asthma",
        "bph",
        "coronary",
        "depression",
        "diabetes",
        "epilepsy",
        "gi_bleeding",
        "glaucoma",
        "heart_failure",
        "hypertension",
        "hyperthyroidism",
        "hypothyroidism",
        "parkinsons",
    ],
    typing.Any,
]
