# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .daily_limit_confidence import DailyLimitConfidence


class DailyLimit(UniversalBaseModel):
    """
    OpenFDA Maximum Daily Dose data
    """

    value_mg: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum daily dose in milligrams
    """

    confidence: typing.Optional[DailyLimitConfidence] = pydantic.Field(default=None)
    """
    Confidence level of the dose calculation
    """

    route: typing.Optional[str] = pydantic.Field(default=None)
    """
    Administration route
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
