# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .clinical_concern import ClinicalConcern


class DrugClinicalData(UniversalBaseModel):
    populations: typing.Optional[typing.Dict[str, ClinicalConcern]] = pydantic.Field(default=None)
    """
    Population-specific data keyed by population name
    """

    conditions: typing.Optional[typing.Dict[str, ClinicalConcern]] = pydantic.Field(default=None)
    """
    Condition-specific data keyed by condition name
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
