# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FoodConflict(UniversalBaseModel):
    """
    A specific food-drug interaction
    """

    food: typing.Optional[str] = pydantic.Field(default=None)
    """
    Food item or food category involved
    """

    severity: typing.Optional[int] = pydantic.Field(default=None)
    """
    Interaction severity (1-5)
    """

    interaction_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pharmacological interaction mechanism
    """

    recommendation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Dietary recommendation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
