# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .interaction_severity_name import InteractionSeverityName


class Interaction(UniversalBaseModel):
    drug1id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="drug_1_id"),
        pydantic.Field(alias="drug_1_id", description="SFX_ID of the first drug in the interaction pair"),
    ] = None
    drug2id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="drug_2_id"),
        pydantic.Field(alias="drug_2_id", description="SFX_ID of the second drug in the interaction pair"),
    ] = None
    severity: typing.Optional[int] = pydantic.Field(default=None)
    """
    Interaction severity level.
    - `2` — Minor: minimal clinical significance
    - `3` — Moderate: may require monitoring or dose adjustment
    - `4` — Major: avoid combination if possible, close monitoring required
    - `5` — Contraindicated: do not use together
    """

    severity_name: typing.Optional[InteractionSeverityName] = pydantic.Field(default=None)
    """
    Human-readable severity label
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Interaction mechanism or clinical description (English)
    """

    description_ar: typing.Optional[str] = pydantic.Field(default=None)
    """
    Interaction description in Arabic
    """

    recommendation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Clinical recommendation for managing this interaction (English)
    """

    recommendation_ar: typing.Optional[str] = pydantic.Field(default=None)
    """
    Clinical recommendation in Arabic
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    Data source
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
