# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InteractionSummary(UniversalBaseModel):
    """
    Interaction count by severity level for quick triage
    """

    contraindicated: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of contraindicated (severity 5) interactions
    """

    major: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of major (severity 4) interactions
    """

    moderate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of moderate (severity 3) interactions
    """

    minor: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of minor (severity 2) interactions
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
