# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .interaction import Interaction
from .interaction_summary import InteractionSummary


class InteractionsData(UniversalBaseModel):
    """
    Drug-drug interaction results. Requires 2 or more resolved drugs.
    If only 1 drug is resolved, returns count=0 with empty interactions array.
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of interactions found
    """

    summary: typing.Optional[InteractionSummary] = None
    interactions: typing.Optional[typing.List[Interaction]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
