# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MetadataResponseDatabaseStats(UniversalBaseModel):
    """
    Database coverage statistics
    """

    ae_products: typing.Optional[int] = pydantic.Field(default=None)
    """
    Products with adverse effect data
    """

    ae_coverage_percent: typing.Optional[float] = pydantic.Field(default=None)
    """
    Percentage of products with AE coverage
    """

    ddi_total_pairs: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total drug-drug interaction pairs
    """

    clinical_conditions: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of supported conditions
    """

    clinical_populations: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of supported populations
    """

    dose_products: typing.Optional[int] = pydantic.Field(default=None)
    """
    Products with dose data
    """

    dose_coverage_percent: typing.Optional[float] = pydantic.Field(default=None)
    """
    Percentage of products with dose coverage
    """

    dose_with_calculation: typing.Optional[int] = pydantic.Field(default=None)
    """
    Products with max units/day calculation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
