# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MetadataResponseRiskScales(UniversalBaseModel):
    """
    Risk/severity scales used across domains
    """

    pllr_pregnancy: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Pregnancy risk scale: integer key → label
    """

    pllr_lactation: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Lactation risk scale: integer key → label
    """

    ae_risk_levels: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Adverse effect risk levels
    """

    ddi_severity: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    DDI severity scale: integer key → label
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
