# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_code import DomainCode
from .meta_tier import MetaTier


class Meta(UniversalBaseModel):
    """
    Request metadata and performance information
    """

    processing_time_ms: typing.Optional[float] = pydantic.Field(default=None)
    """
    Server-side processing time in milliseconds
    """

    domains_checked: typing.Optional[typing.List[DomainCode]] = pydantic.Field(default=None)
    """
    Domains that were actually checked
    """

    drug_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of drugs submitted
    """

    resolved_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of drugs successfully resolved
    """

    unresolved_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of drugs that could not be resolved
    """

    tier: typing.Optional[MetaTier] = pydantic.Field(default=None)
    """
    Caller's current tier
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
