# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MetadataResponseDatabaseVersions(UniversalBaseModel):
    """
    Current database versions
    """

    ae: typing.Optional[str] = None
    ddi: typing.Optional[str] = None
    clinical: typing.Optional[str] = None
    pllr: typing.Optional[str] = None
    food: typing.Optional[str] = None
    dose: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
