# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .condition import Condition
from .population import Population


class PatientProfile(UniversalBaseModel):
    """
    Patient context for personalized safety screening. When provided,
    the `clinical` domain returns population-specific warnings and
    condition-drug interaction alerts tailored to this patient.
    """

    populations: typing.Optional[typing.List[Population]] = pydantic.Field(default=None)
    """
    Patient populations (e.g., geriatric, renal impairment)
    """

    conditions: typing.Optional[typing.List[Condition]] = pydantic.Field(default=None)
    """
    Patient comorbidities (e.g., diabetes, hypertension)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
