# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PopulationMonitoringLiverFunctionGrades(UniversalBaseModel):
    """
    Child-Pugh grade contraindication status (hepatic population)
    """

    a: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="A"), pydantic.Field(alias="A")] = None
    b: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="B"), pydantic.Field(alias="B")] = None
    c: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="C"), pydantic.Field(alias="C")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
