# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReferenceDose(UniversalBaseModel):
    """
    WHO Defined Daily Dose (DDD) reference data
    """

    value: typing.Optional[float] = pydantic.Field(default=None)
    """
    DDD value
    """

    unit: typing.Optional[str] = pydantic.Field(default=None)
    """
    DDD unit (g, mg, etc.)
    """

    units_per_ddd: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of dosage units per DDD
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
