# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .reproductive_warning import ReproductiveWarning


class ReproductiveSafetyData(UniversalBaseModel):
    """
    Pregnancy and lactation safety data for a single drug
    """

    pregnancy_risk_level: typing.Optional[int] = pydantic.Field(default=None)
    """
    Pregnancy risk score on the SafeRx 0-7 scale.
    - `0` — Unknown
    - `1` — Safe
    - `2` — Likely Safe
    - `3` — Possibly Unsafe
    - `4` — Likely Unsafe
    - `5` — Unsafe
    - `6` — Contraindicated
    - `7` — Absolutely Contraindicated
    """

    pregnancy_risk_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable pregnancy risk label
    """

    lactation_risk_level: typing.Optional[int] = pydantic.Field(default=None)
    """
    Lactation risk score (same 0-7 scale as pregnancy)
    """

    lactation_risk_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable lactation risk label
    """

    pregnancy_rationale: typing.Optional[str] = pydantic.Field(default=None)
    """
    Clinical rationale for the pregnancy risk rating (language depends on `lang` parameter)
    """

    lactation_rationale: typing.Optional[str] = pydantic.Field(default=None)
    """
    Clinical rationale for the lactation risk rating
    """

    pregnancy_warning: typing.Optional[ReproductiveWarning] = None
    lactation_warning: typing.Optional[ReproductiveWarning] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
