// This file was auto-generated by Fern from our API Definition.

export type CreateFreeKeyDevelopersResponse =
    /**
     * New user - code sent */
    | {
          message?: string | undefined;
          email?: string | undefined;
      }
    /**
     * Existing verified user - key returned */
    | {
          api_key?: string | undefined;
          tier?: string | undefined;
          limits?:
              | {
                    requests_per_minute?: number | undefined;
                    requests_per_day?: number | undefined;
                }
              | undefined;
          note?: string | undefined;
      };
