// This file was auto-generated by Fern from our API Definition.

export interface VerifyFreeKeyDevelopersResponse {
    /** Your persistent free-tier API key */
    api_key?: string | undefined;
    tier?: string | undefined;
    limits?: VerifyFreeKeyDevelopersResponse.Limits | undefined;
}

export namespace VerifyFreeKeyDevelopersResponse {
    export interface Limits {
        requests_per_minute?: number | undefined;
        requests_per_day?: number | undefined;
    }
}
