# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .environment import SafeRxClientEnvironment

if typing.TYPE_CHECKING:
    from .developers.client import AsyncDevelopersClient, DevelopersClient
    from .drug_safety.client import AsyncDrugSafetyClient, DrugSafetyClient


class SafeRxClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : SafeRxClientEnvironment
        The environment to use for requests from the client. from .environment import SafeRxClientEnvironment



        Defaults to SafeRxClientEnvironment.PRODUCTION



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from saferx import SafeRxClient

    client = SafeRxClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: SafeRxClientEnvironment = SafeRxClientEnvironment.PRODUCTION,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._drug_safety: typing.Optional[DrugSafetyClient] = None
        self._developers: typing.Optional[DevelopersClient] = None

    @property
    def drug_safety(self):
        if self._drug_safety is None:
            from .drug_safety.client import DrugSafetyClient  # noqa: E402

            self._drug_safety = DrugSafetyClient(client_wrapper=self._client_wrapper)
        return self._drug_safety

    @property
    def developers(self):
        if self._developers is None:
            from .developers.client import DevelopersClient  # noqa: E402

            self._developers = DevelopersClient(client_wrapper=self._client_wrapper)
        return self._developers


class AsyncSafeRxClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : SafeRxClientEnvironment
        The environment to use for requests from the client. from .environment import SafeRxClientEnvironment



        Defaults to SafeRxClientEnvironment.PRODUCTION



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from saferx import AsyncSafeRxClient

    client = AsyncSafeRxClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: SafeRxClientEnvironment = SafeRxClientEnvironment.PRODUCTION,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._drug_safety: typing.Optional[AsyncDrugSafetyClient] = None
        self._developers: typing.Optional[AsyncDevelopersClient] = None

    @property
    def drug_safety(self):
        if self._drug_safety is None:
            from .drug_safety.client import AsyncDrugSafetyClient  # noqa: E402

            self._drug_safety = AsyncDrugSafetyClient(client_wrapper=self._client_wrapper)
        return self._drug_safety

    @property
    def developers(self):
        if self._developers is None:
            from .developers.client import AsyncDevelopersClient  # noqa: E402

            self._developers = AsyncDevelopersClient(client_wrapper=self._client_wrapper)
        return self._developers


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: SafeRxClientEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
