# This file was auto-generated by Fern from our API Definition.

import typing

from .create_free_key_developers_response_api_key import CreateFreeKeyDevelopersResponseApiKey
from .create_free_key_developers_response_email import CreateFreeKeyDevelopersResponseEmail

CreateFreeKeyDevelopersResponse = typing.Union[
    CreateFreeKeyDevelopersResponseEmail, CreateFreeKeyDevelopersResponseApiKey
]
