# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_free_key_developers_response_api_key_limits import CreateFreeKeyDevelopersResponseApiKeyLimits


class CreateFreeKeyDevelopersResponseApiKey(UniversalBaseModel):
    """
    Existing verified user - key returned
    """

    api_key: typing.Optional[str] = None
    tier: typing.Optional[str] = None
    limits: typing.Optional[CreateFreeKeyDevelopersResponseApiKeyLimits] = None
    note: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
