# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .verify_free_key_developers_response_limits import VerifyFreeKeyDevelopersResponseLimits


class VerifyFreeKeyDevelopersResponse(UniversalBaseModel):
    api_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Your persistent free-tier API key
    """

    tier: typing.Optional[str] = None
    limits: typing.Optional[VerifyFreeKeyDevelopersResponseLimits] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
