// This file was auto-generated by Fern from our API Definition.

export interface GetDrugSafetyHealthResponse {
    status?: GetDrugSafetyHealthResponse.Status | undefined;
    subsystem?: string | undefined;
    checks?: Record<string, GetDrugSafetyHealthResponse.Checks.Value> | undefined;
    latency_ms?: number | undefined;
}

export namespace GetDrugSafetyHealthResponse {
    export const Status = {
        Healthy: "healthy",
        Degraded: "degraded",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export namespace Checks {
        export interface Value {
            status?: Value.Status | undefined;
        }

        export namespace Value {
            export const Status = {
                Healthy: "healthy",
                Degraded: "degraded",
                Unhealthy: "unhealthy",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
