// This file was auto-generated by Fern from our API Definition.

export interface AdverseEffect {
    /** Adverse effect name in English */
    effect_name?: string | undefined;
    /** Effect name in Arabic */
    name_ar?: string | undefined;
    /** Frequency as a decimal (0.0 to 1.0) */
    frequency?: number | undefined;
    /** Human-readable frequency tier */
    frequency_label?: string | undefined;
    /** Numeric frequency tier (1=very rare, 5=very common) */
    frequency_category?: number | undefined;
    /** Detailed frequency breakdown */
    frequency_detail?: AdverseEffect.FrequencyDetail | undefined;
    /** Severity score (1=mild, 5=life-threatening) */
    severity?: number | undefined;
    /** Human-readable severity label */
    severity_label?: string | undefined;
    /**
     * Severity category name (mild, moderate, serious,
     * severe, life_threatening)
     */
    severity_category?: string | undefined;
    /** Data source for this effect */
    source?: string | undefined;
    /** Brief clinical guidance */
    clinical_advice?: string | undefined;
    /** Whether monitoring is recommended */
    requires_monitoring?: boolean | undefined;
    /** Whether this effect requires urgent attention */
    urgency?: boolean | undefined;
    /** Classification basis for this effect */
    basis?: string | undefined;
}

export namespace AdverseEffect {
    /**
     * Detailed frequency breakdown
     */
    export interface FrequencyDetail {
        category?: string | undefined;
        label?: string | undefined;
        value?: number | undefined;
    }
}
