// This file was auto-generated by Fern from our API Definition.

/**
 * High-severity safety alert bubbled up from domain-level data.
 * Alerts are generated when safety thresholds are exceeded.
 */
export interface Alert {
    /**
     * Alert severity level.
     * - `CRITICAL` — Immediate action required (e.g., BBW, contraindicated DDI, pregnancy risk 7)
     * - `HIGH` — Significant risk requiring pharmacist review (e.g., major DDI, pregnancy risk 6)
     * - `MODERATE` — Worth noting, may require monitoring
     * - `LOW` — Informational
     */
    severity: Alert.Severity;
    /**
     * Alert source domain and trigger.
     * - `ae_bbw` — Drug has a Black Box Warning
     * - `ddi` — Major (severity 4) or contraindicated (severity 5) interaction
     * - `pllr_pregnancy` — Pregnancy risk >= 6 (Contraindicated or Absolutely Contraindicated)
     * - `pllr_lactation` — Lactation risk >= 6
     * - `clinical_condition` — Clinical condition severity >= 4
     * - `clinical_population` — Clinical population severity >= 4
     */
    type: Alert.Type;
    /** Human-readable alert message */
    message: string;
    /** Drug names involved in this alert */
    drugs_involved: string[];
}

export namespace Alert {
    /**
     * Alert severity level.
     * - `CRITICAL` — Immediate action required (e.g., BBW, contraindicated DDI, pregnancy risk 7)
     * - `HIGH` — Significant risk requiring pharmacist review (e.g., major DDI, pregnancy risk 6)
     * - `MODERATE` — Worth noting, may require monitoring
     * - `LOW` — Informational
     */
    export const Severity = {
        Critical: "CRITICAL",
        High: "HIGH",
        Moderate: "MODERATE",
        Low: "LOW",
    } as const;
    export type Severity = (typeof Severity)[keyof typeof Severity];
    /**
     * Alert source domain and trigger.
     * - `ae_bbw` — Drug has a Black Box Warning
     * - `ddi` — Major (severity 4) or contraindicated (severity 5) interaction
     * - `pllr_pregnancy` — Pregnancy risk >= 6 (Contraindicated or Absolutely Contraindicated)
     * - `pllr_lactation` — Lactation risk >= 6
     * - `clinical_condition` — Clinical condition severity >= 4
     * - `clinical_population` — Clinical population severity >= 4
     */
    export const Type = {
        AeBbw: "ae_bbw",
        Ddi: "ddi",
        PllrPregnancy: "pllr_pregnancy",
        PllrLactation: "pllr_lactation",
        ClinicalCondition: "clinical_condition",
        ClinicalPopulation: "clinical_population",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
