// This file was auto-generated by Fern from our API Definition.

export interface BlackBoxWarning {
    /** Full BBW text in English */
    warning_text?: string | undefined;
    /** Full BBW text in Arabic */
    warning_text_ar?: string | undefined;
    /**
     * BBW category tags (e.g., DEATH_RISK, BLEEDING_RISK, CARDIAC_RISK,
     * HEPATOTOXICITY, SUICIDALITY, TERATOGENIC)
     */
    categories?: string[] | undefined;
    /** Whether this BBW includes a mortality risk */
    has_death_warning?: boolean | undefined;
    /** Source of the BBW data */
    source?: string | undefined;
}
