// This file was auto-generated by Fern from our API Definition.

/**
 * Response when access is temporarily suspended
 */
export interface BlockedResponse {
    error?: string | undefined;
    reason?: string | undefined;
    message?: string | undefined;
    support?: string | undefined;
}
