// This file was auto-generated by Fern from our API Definition.

/**
 * Clinical safety alert from cross-drug analysis
 */
export interface ClinicalAlert {
    /** SFX_ID of the drug involved */
    drug_id?: string | undefined;
    /** Drug name (English) */
    drug?: string | undefined;
    /** Drug name (Arabic) */
    drug_ar?: string | undefined;
    /** Condition name (for condition alerts) */
    condition?: string | undefined;
    /** Condition name in Arabic */
    condition_ar?: string | undefined;
    /** Population name (for population alerts) */
    population?: string | undefined;
    /** Population name in Arabic */
    population_ar?: string | undefined;
    /** Alert severity */
    severity?: number | undefined;
    /** Severity label (English) */
    severity_label?: string | undefined;
    /** Severity label (Arabic) */
    severity_label_ar?: string | undefined;
    /** Whether the drug is contraindicated for this population/condition */
    contraindicated?: boolean | undefined;
    /** Whether dose adjustment is needed */
    requires_dose_adjustment?: boolean | undefined;
    /** Whether additional monitoring is needed */
    monitoring_required?: boolean | undefined;
    /** Clinical rationale (English) */
    reason?: string | undefined;
    /** Clinical rationale (Arabic) */
    reason_ar?: string | undefined;
    /** Data source */
    source?: string | undefined;
    /** Additional clinical notes */
    special_notes?: ClinicalAlert.SpecialNotes | undefined;
}

export namespace ClinicalAlert {
    /**
     * Additional clinical notes
     */
    export interface SpecialNotes {
        /** Whether this drug is flagged as high-risk for elderly patients */
        geriatric_high_risk?: boolean | undefined;
    }
}
