// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Clinical safety considerations combining per-drug population/condition
 * data with cross-drug clinical alerts. Enhanced when `patient_profile`
 * is provided in the request.
 */
export interface ClinicalData {
    /** Per-drug clinical data keyed by SFX_ID */
    drug_specific?: Record<string, SafeRx.DrugClinicalData> | undefined;
    /** Cross-drug condition-related alerts (requires `patient_profile.conditions`) */
    condition_alerts?: SafeRx.ClinicalAlert[] | undefined;
    /** Cross-drug population-related alerts (requires `patient_profile.populations`) */
    population_alerts?: SafeRx.ClinicalAlert[] | undefined;
}
