// This file was auto-generated by Fern from our API Definition.

/**
 * Clinical concern for a specific population or condition
 */
export interface ClinicalConcern {
    /** Drug name */
    name?: string | undefined;
    /** Concern severity (1=minor, 5=contraindicated) */
    severity?: number | undefined;
    /** Human-readable severity label */
    severity_name?: string | undefined;
    /** Clinical rationale */
    reason?: string | undefined;
    /** Data source */
    source?: string | undefined;
}
