// This file was auto-generated by Fern from our API Definition.

/**
 * Patient comorbidity. Used by the `clinical` domain to identify
 * drugs that are contraindicated or require caution for patients
 * with these conditions.
 */
export const Condition = {
    Arrhythmia: "arrhythmia",
    Asthma: "asthma",
    Bph: "bph",
    Coronary: "coronary",
    Depression: "depression",
    Diabetes: "diabetes",
    Epilepsy: "epilepsy",
    GiBleeding: "gi_bleeding",
    Glaucoma: "glaucoma",
    HeartFailure: "heart_failure",
    Hypertension: "hypertension",
    Hyperthyroidism: "hyperthyroidism",
    Hypothyroidism: "hypothyroidism",
    Parkinsons: "parkinsons",
} as const;
export type Condition = (typeof Condition)[keyof typeof Condition];
