// This file was auto-generated by Fern from our API Definition.

/**
 * OpenFDA Maximum Daily Dose data
 */
export interface DailyLimit {
    /** Maximum daily dose in milligrams */
    value_mg?: number | undefined;
    /** Confidence level of the dose calculation */
    confidence?: DailyLimit.Confidence | undefined;
    /** Administration route */
    route?: string | undefined;
}

export namespace DailyLimit {
    /** Confidence level of the dose calculation */
    export const Confidence = {
        High: "high",
        Medium: "medium",
        Low: "low",
    } as const;
    export type Confidence = (typeof Confidence)[keyof typeof Confidence];
}
