// This file was auto-generated by Fern from our API Definition.

/**
 * Safety domain identifier.
 * - `ae` — Adverse effects, Black Box Warnings, monitoring parameters
 * - `ddi` — Drug-drug interactions (requires 2+ drugs)
 * - `pllr` — Pregnancy & lactation risk ratings
 * - `food` — Meal timing & food-drug conflicts
 * - `clinical` — Population & condition safety (enhanced with `patient_profile`)
 * - `dose` — Maximum daily dose (V3: dual-source, 19K+ products, tier-based safety)
 */
export const DomainCode = {
    Ae: "ae",
    Ddi: "ddi",
    Pllr: "pllr",
    Food: "food",
    Clinical: "clinical",
    Dose: "dose",
} as const;
export type DomainCode = (typeof DomainCode)[keyof typeof DomainCode];
