// This file was auto-generated by Fern from our API Definition.

/**
 * Per-ingredient dose data for combination drugs
 */
export interface DoseComponent {
    /** Maximum daily dose for this ingredient in mg */
    value_mg?: number | undefined;
    original_value?: number | undefined;
    original_unit?: string | undefined;
    route?: string | undefined;
    confidence?: DoseComponent.Confidence | undefined;
    confidence_reason?: string | undefined;
    /** Typical daily dose range */
    usual_range?: string | undefined;
    max_single_dose_mg?: number | undefined;
    /** Whether dosing is weight-based */
    weight_based?: boolean | undefined;
    /** Weight-based dosing if applicable */
    weight_dose?: string | undefined;
    /** Whether max dose varies by indication */
    indication_specific?: boolean | undefined;
    indication_note?: string | undefined;
}

export namespace DoseComponent {
    export const Confidence = {
        High: "high",
        Medium: "medium",
        Low: "low",
    } as const;
    export type Confidence = (typeof Confidence)[keyof typeof Confidence];
}
