// This file was auto-generated by Fern from our API Definition.

/**
 * WHO DDD-based dose-response classification.
 * Type A reactions are dose-dependent and predictable.
 * Type B reactions are idiosyncratic and unpredictable.
 */
export interface DoseClassification {
    /**
     * Primary reaction type.
     * - `A` — Dose-dependent (augmented). Predictable from pharmacology.
     * - `B` — Idiosyncratic (bizarre). Unpredictable, not dose-related.
     */
    reaction_type?: DoseClassification.ReactionType | undefined;
    /** Classification rationale */
    basis?: string | undefined;
    /** Whether any idiosyncratic (Type B) reactions exist */
    has_idiosyncratic?: boolean | undefined;
    /** List of known idiosyncratic effects */
    idiosyncratic_effects?: string[] | undefined;
    /** Confidence in the classification */
    confidence?: DoseClassification.Confidence | undefined;
}

export namespace DoseClassification {
    /**
     * Primary reaction type.
     * - `A` — Dose-dependent (augmented). Predictable from pharmacology.
     * - `B` — Idiosyncratic (bizarre). Unpredictable, not dose-related.
     */
    export const ReactionType = {
        A: "A",
        B: "B",
    } as const;
    export type ReactionType = (typeof ReactionType)[keyof typeof ReactionType];
    /** Confidence in the classification */
    export const Confidence = {
        High: "high",
        Medium: "medium",
        Low: "low",
    } as const;
    export type Confidence = (typeof Confidence)[keyof typeof Confidence];
}
