// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Maximum daily dose data from Dose V3 — dual-source system combining
 * WHO Defined Daily Dose (DDD) and OpenFDA Maximum Daily Dose (MDD).
 * Covers 19,341 products (67.7% of database) with tier-based safety calculations.
 */
export interface DosingData {
    /**
     * Data quality tier.
     * - `1` — Full reference data (WHO DDD + OpenFDA MDD available)
     * - `2` — Regulatory label data only
     */
    tier?: number | undefined;
    /** Maximum safe units (tablets, capsules) per day */
    max_units_per_day?: (number | null) | undefined;
    /** Maximum safe volume per day for liquid forms */
    max_ml_per_day?: (number | null) | undefined;
    /** Unit type (tablets, capsules, ml, etc.) */
    unit_label?: string | undefined;
    /** Whether dose calculation has caveats requiring attention */
    flagged?: boolean | undefined;
    /** Reason if dose calculation was skipped (e.g., topical, inhaled) */
    skip_reason?: (string | null) | undefined;
    /** Important caveat about the dose calculation */
    caveat?: (string | null) | undefined;
    /** WHO DDD reference dose data */
    reference_dose?: (SafeRx.ReferenceDose | null) | undefined;
    /** OpenFDA maximum daily dose data */
    daily_limit?: (SafeRx.DailyLimit | null) | undefined;
    /** Per-ingredient dose data for combination drugs */
    components?: ((SafeRx.DoseComponent | null)[] | null) | undefined;
    /**
     * Data source for this dose calculation.
     * - `reference_standard` — WHO DDD only
     * - `regulatory_label` — OpenFDA MDD only
     * - `dual_source` — Both WHO DDD and OpenFDA MDD available
     */
    source?: DosingData.Source | undefined;
}

export namespace DosingData {
    /**
     * Data source for this dose calculation.
     * - `reference_standard` — WHO DDD only
     * - `regulatory_label` — OpenFDA MDD only
     * - `dual_source` — Both WHO DDD and OpenFDA MDD available
     */
    export const Source = {
        ReferenceStandard: "reference_standard",
        RegulatoryLabel: "regulatory_label",
        DualSource: "dual_source",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
}
