// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

export interface DrugClinicalData {
    /** Population-specific data keyed by population name */
    populations?: Record<string, SafeRx.ClinicalConcern> | undefined;
    /** Condition-specific data keyed by condition name */
    conditions?: Record<string, SafeRx.ClinicalConcern> | undefined;
}
