// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

export interface DrugSafetyCheckResponse {
    /** Always `"success"` for 200 responses */
    status: DrugSafetyCheckResponse.Status;
    /** Successfully resolved drugs with full product details */
    drugs: SafeRx.ResolvedDrug[];
    /**
     * Drug names that could not be resolved to a SafeRx product.
     * These are not errors — they simply did not match any product
     * with sufficient confidence.
     */
    unresolved: string[];
    safety: SafeRx.SafetyData;
    /**
     * High-severity safety issues bubbled up from all domains, sorted
     * by severity (CRITICAL first). Use this array for quick triage —
     * it contains the most actionable items from the full safety data.
     */
    alerts: SafeRx.Alert[];
    meta: SafeRx.Meta;
}

export namespace DrugSafetyCheckResponse {
    /** Always `"success"` for 200 responses */
    export const Status = {
        Success: "success",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
