// This file was auto-generated by Fern from our API Definition.

export interface ErrorResponse {
    /** Error indicator or error message */
    error?: ErrorResponse.Error_ | undefined;
    /** Machine-readable error code */
    code?: string | undefined;
    /** Human-readable error description */
    message?: string | undefined;
    /** HTTP status code */
    status?: number | undefined;
    /** API tier of the caller (present on limit errors) */
    tier?: string | undefined;
    /** Number of items submitted (present on count limit errors) */
    your_count?: number | undefined;
    /** Upgrade guidance */
    hint?: string | undefined;
    /** Support email for assistance */
    support?: string | undefined;
}

export namespace ErrorResponse {
    /**
     * Error indicator or error message
     */
    export type Error_ = boolean | string;
}
