// This file was auto-generated by Fern from our API Definition.

/**
 * A specific food-drug interaction
 */
export interface FoodConflict {
    /** Food item or food category involved */
    food?: string | undefined;
    /** Interaction severity (1-5) */
    severity?: number | undefined;
    /** Pharmacological interaction mechanism */
    interaction_type?: string | undefined;
    /** Dietary recommendation */
    recommendation?: string | undefined;
}
