// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Food-drug interaction data for a single drug
 */
export interface FoodData {
    timing?: SafeRx.MealTiming | undefined;
    /** Specific food-drug conflicts */
    conflicts?: SafeRx.FoodConflict[] | undefined;
    /** Total number of food conflicts (may exceed items in `conflicts` array) */
    conflict_count?: number | undefined;
}
