// This file was auto-generated by Fern from our API Definition.

/**
 * Interaction count by severity level for quick triage
 */
export interface InteractionSummary {
    /** Number of contraindicated (severity 5) interactions */
    contraindicated?: number | undefined;
    /** Number of major (severity 4) interactions */
    major?: number | undefined;
    /** Number of moderate (severity 3) interactions */
    moderate?: number | undefined;
    /** Number of minor (severity 2) interactions */
    minor?: number | undefined;
}
