// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Drug-drug interaction results. Requires 2 or more resolved drugs.
 * If only 1 drug is resolved, returns count=0 with empty interactions array.
 */
export interface InteractionsData {
    /** Total number of interactions found */
    count?: number | undefined;
    summary?: SafeRx.InteractionSummary | undefined;
    interactions?: SafeRx.Interaction[] | undefined;
}
