// This file was auto-generated by Fern from our API Definition.

export interface Interaction {
    /** SFX_ID of the first drug in the interaction pair */
    drug_1_id?: string | undefined;
    /** SFX_ID of the second drug in the interaction pair */
    drug_2_id?: string | undefined;
    /**
     * Interaction severity level.
     * - `2` — Minor: minimal clinical significance
     * - `3` — Moderate: may require monitoring or dose adjustment
     * - `4` — Major: avoid combination if possible, close monitoring required
     * - `5` — Contraindicated: do not use together
     */
    severity?: number | undefined;
    /** Human-readable severity label */
    severity_name?: Interaction.SeverityName | undefined;
    /** Interaction mechanism or clinical description (English) */
    description?: string | undefined;
    /** Interaction description in Arabic */
    description_ar?: string | undefined;
    /** Clinical recommendation for managing this interaction (English) */
    recommendation?: string | undefined;
    /** Clinical recommendation in Arabic */
    recommendation_ar?: string | undefined;
    /** Data source */
    source?: string | undefined;
}

export namespace Interaction {
    /** Human-readable severity label */
    export const SeverityName = {
        Minor: "MINOR",
        Moderate: "MODERATE",
        Major: "MAJOR",
        Contraindicated: "CONTRAINDICATED",
    } as const;
    export type SeverityName = (typeof SeverityName)[keyof typeof SeverityName];
}
