// This file was auto-generated by Fern from our API Definition.

/**
 * Meal timing recommendation
 */
export interface MealTiming {
    /**
     * Timing category code.
     * Common values: `WITH_FOOD`, `EMPTY_STOMACH`, `WITH_OR_WITHOUT_FOOD`,
     * `NO_RESTRICTION`, `BEFORE_MEALS`, `AFTER_MEALS`
     */
    category?: string | undefined;
    /**
     * How important is adherence to this timing.
     * Values: `MUST`, `PREFERRED`, `OPTIONAL`, `NO_RESTRICTION`
     */
    importance?: string | undefined;
    /** Full recommendation text (English) */
    recommendation?: string | undefined;
    /** Full recommendation text (Arabic) */
    recommendation_ar?: string | undefined;
    /** Evidence source for this recommendation */
    evidence_level?: string | undefined;
    /** Severity of non-adherence consequences (1-5) */
    severity?: number | undefined;
    /** Clinical rationale for the timing recommendation */
    rationale?: string | undefined;
}
