// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

export interface MetadataResponse {
    status: MetadataResponse.Status;
    /** Maximum drugs allowed per request for your tier */
    max_drugs_per_request?: number | undefined;
    /** All available safety domains */
    available_domains: SafeRx.DomainCode[];
    /** Valid values for the `patient_profile` field */
    patient_profile_options: MetadataResponse.PatientProfileOptions;
    /** Risk/severity scales used across domains */
    risk_scales: MetadataResponse.RiskScales;
    /** Current database versions */
    database_versions?: MetadataResponse.DatabaseVersions | undefined;
    /** Database coverage statistics */
    database_stats?: MetadataResponse.DatabaseStats | undefined;
    /** Supported response languages */
    supported_languages?: string[] | undefined;
    /** Caller's current tier */
    tier?: MetadataResponse.Tier | undefined;
}

export namespace MetadataResponse {
    export const Status = {
        Success: "success",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * Valid values for the `patient_profile` field
     */
    export interface PatientProfileOptions {
        populations?: SafeRx.Population[] | undefined;
        conditions?: SafeRx.Condition[] | undefined;
    }

    /**
     * Risk/severity scales used across domains
     */
    export interface RiskScales {
        /** Pregnancy risk scale: integer key → label */
        pllr_pregnancy?: Record<string, string> | undefined;
        /** Lactation risk scale: integer key → label */
        pllr_lactation?: Record<string, string> | undefined;
        /** Adverse effect risk levels */
        ae_risk_levels?: string[] | undefined;
        /** DDI severity scale: integer key → label */
        ddi_severity?: Record<string, string> | undefined;
    }

    /**
     * Current database versions
     */
    export interface DatabaseVersions {
        ae?: string | undefined;
        ddi?: string | undefined;
        clinical?: string | undefined;
        pllr?: string | undefined;
        food?: string | undefined;
        dose?: string | undefined;
    }

    /**
     * Database coverage statistics
     */
    export interface DatabaseStats {
        /** Products with adverse effect data */
        ae_products?: number | undefined;
        /** Percentage of products with AE coverage */
        ae_coverage_percent?: number | undefined;
        /** Total drug-drug interaction pairs */
        ddi_total_pairs?: number | undefined;
        /** Number of supported conditions */
        clinical_conditions?: number | undefined;
        /** Number of supported populations */
        clinical_populations?: number | undefined;
        /** Products with dose data */
        dose_products?: number | undefined;
        /** Percentage of products with dose coverage */
        dose_coverage_percent?: number | undefined;
        /** Products with max units/day calculation */
        dose_with_calculation?: number | undefined;
    }

    /** Caller's current tier */
    export const Tier = {
        Free: "free",
        Pro: "pro",
        Enterprise: "enterprise",
    } as const;
    export type Tier = (typeof Tier)[keyof typeof Tier];
}
