// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Request metadata and performance information
 */
export interface Meta {
    /** Server-side processing time in milliseconds */
    processing_time_ms?: number | undefined;
    /** Domains that were actually checked */
    domains_checked?: SafeRx.DomainCode[] | undefined;
    /** Number of drugs submitted */
    drug_count?: number | undefined;
    /** Number of drugs successfully resolved */
    resolved_count?: number | undefined;
    /** Number of drugs that could not be resolved */
    unresolved_count?: number | undefined;
    /** Caller's current tier */
    tier?: Meta.Tier | undefined;
}

export namespace Meta {
    /** Caller's current tier */
    export const Tier = {
        Free: "free",
        Pro: "pro",
        Enterprise: "enterprise",
    } as const;
    export type Tier = (typeof Tier)[keyof typeof Tier];
}
