// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Recommended monitoring parameters for this drug
 */
export interface Monitoring {
    /** Drug name for context */
    drug?: string | undefined;
    /** Lab tests and clinical parameters to monitor */
    parameters?: string[] | undefined;
    /** Recommended monitoring frequency */
    schedule?: string | undefined;
    /** Contraindication notes */
    contraindications?: string[] | undefined;
    /** Population-specific monitoring considerations */
    populations?: Record<string, SafeRx.PopulationMonitoring> | undefined;
    /** Maximum daily dose information, if available */
    daily_dose_limit?: (SafeRx.DailyLimit | null) | undefined;
    /** Whether this drug has a BBW (duplicated for convenience) */
    has_black_box_warning?: boolean | undefined;
    /** Data sources used for monitoring recommendations */
    data_sources?: string[] | undefined;
}
