// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Patient context for personalized safety screening. When provided,
 * the `clinical` domain returns population-specific warnings and
 * condition-drug interaction alerts tailored to this patient.
 */
export interface PatientProfile {
    /** Patient populations (e.g., geriatric, renal impairment) */
    populations?: SafeRx.Population[] | undefined;
    /** Patient comorbidities (e.g., diabetes, hypertension) */
    conditions?: SafeRx.Condition[] | undefined;
}
