// This file was auto-generated by Fern from our API Definition.

/**
 * Special patient population.
 * - `pediatric` — children and adolescents
 * - `geriatric` — elderly patients (65+)
 * - `cardiac` — patients with cardiac conditions
 * - `hepatic` — patients with liver impairment
 * - `renal` — patients with kidney impairment
 */
export const Population = {
    Pediatric: "pediatric",
    Geriatric: "geriatric",
    Cardiac: "cardiac",
    Hepatic: "hepatic",
    Renal: "renal",
} as const;
export type Population = (typeof Population)[keyof typeof Population];
