// This file was auto-generated by Fern from our API Definition.

export interface PopulationMonitoring {
    /** Drug name */
    name?: string | undefined;
    /** Whether the drug is contraindicated in this population */
    contraindicated?: boolean | undefined;
    /** Whether eGFR monitoring is needed (renal population) */
    requires_egfr_check?: boolean | undefined;
    /** Whether dialysis considerations apply (renal population) */
    requires_dialysis_check?: boolean | undefined;
    /** Child-Pugh grade contraindication status (hepatic population) */
    liver_function_grades?: PopulationMonitoring.LiverFunctionGrades | undefined;
    /** Severity in this population (1-5) */
    severity?: number | undefined;
    /** Severity label in this population */
    severity_label?: string | undefined;
}

export namespace PopulationMonitoring {
    /**
     * Child-Pugh grade contraindication status (hepatic population)
     */
    export interface LiverFunctionGrades {
        A?: boolean | undefined;
        B?: boolean | undefined;
        C?: boolean | undefined;
    }
}
