// This file was auto-generated by Fern from our API Definition.

/**
 * Response when rate limit is exceeded
 */
export interface RateLimitResponse {
    error?: string | undefined;
    /** Your per-minute limit */
    limit_per_minute?: number | undefined;
    /** Requests made in the current minute */
    requests_this_minute?: number | undefined;
    /** Your daily limit (present on daily limit errors) */
    daily_limit?: number | undefined;
    /** Requests made today (present on daily limit errors) */
    requests_today?: number | undefined;
    tier?: RateLimitResponse.Tier | undefined;
    /** Upgrade guidance */
    hint?: string | undefined;
    support?: string | undefined;
}

export namespace RateLimitResponse {
    export const Tier = {
        Free: "free",
        Pro: "pro",
        Enterprise: "enterprise",
    } as const;
    export type Tier = (typeof Tier)[keyof typeof Tier];
}
