// This file was auto-generated by Fern from our API Definition.

/**
 * WHO Defined Daily Dose (DDD) reference data
 */
export interface ReferenceDose {
    /** DDD value */
    value?: number | undefined;
    /** DDD unit (g, mg, etc.) */
    unit?: string | undefined;
    /** Number of dosage units per DDD */
    units_per_ddd?: number | undefined;
}
