// This file was auto-generated by Fern from our API Definition.

/**
 * Pregnancy or lactation specific warning
 */
export interface ReproductiveWarning {
    /** Whether a specific warning exists */
    has_warning?: boolean | undefined;
    /** Warning text (language depends on `lang` parameter) */
    text?: (string | null) | undefined;
    /** Warning categories */
    categories?: string[] | undefined;
}
