// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Pregnancy and lactation safety data for a single drug
 */
export interface ReproductiveSafetyData {
    /**
     * Pregnancy risk score on the SafeRx 0-7 scale.
     * - `0` — Unknown
     * - `1` — Safe
     * - `2` — Likely Safe
     * - `3` — Possibly Unsafe
     * - `4` — Likely Unsafe
     * - `5` — Unsafe
     * - `6` — Contraindicated
     * - `7` — Absolutely Contraindicated
     */
    pregnancy_risk_level?: number | undefined;
    /** Human-readable pregnancy risk label */
    pregnancy_risk_name?: string | undefined;
    /** Lactation risk score (same 0-7 scale as pregnancy) */
    lactation_risk_level?: number | undefined;
    /** Human-readable lactation risk label */
    lactation_risk_name?: string | undefined;
    /** Clinical rationale for the pregnancy risk rating (language depends on `lang` parameter) */
    pregnancy_rationale?: string | undefined;
    /** Clinical rationale for the lactation risk rating */
    lactation_rationale?: string | undefined;
    pregnancy_warning?: SafeRx.ReproductiveWarning | undefined;
    lactation_warning?: SafeRx.ReproductiveWarning | undefined;
}
