// This file was auto-generated by Fern from our API Definition.

export interface ResolvedDrug {
    /** The original drug name as submitted in the request */
    input: string;
    /** Always `true` for drugs in this array */
    resolved: boolean;
    /**
     * SafeRx product identifier. Primary key used across all safety
     * domains. Format: `SRX-{category}-{sequence}`.
     */
    SFX_ID: string;
    /** Registered trade name with strength and pack size */
    brand_name: string;
    /** Active pharmaceutical ingredient(s), pipe-separated for combinations */
    active_ingredient: string;
    /** Pharmaceutical dosage form */
    form: string;
    /** Marketing authorization holder */
    manufacturer?: string | undefined;
    /** ATC-based therapeutic classification, pipe-separated hierarchy */
    therapeutic_class?: string | undefined;
    /** Primary prescribing specialty */
    medical_specialty?: string | undefined;
    /** Distribution company (may be empty) */
    distributor?: string | undefined;
    /** Product barcode (may be empty) */
    barcode?: string | undefined;
    /** Current price in Egyptian Pounds (EGP) */
    price_egp?: number | undefined;
}
