// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

/**
 * Safety screening results organized by domain. Each domain key maps
 * to domain-specific data. Domains not requested via `include` will
 * be absent from this object.
 */
export interface SafetyData {
    /**
     * Adverse effects data keyed by SFX_ID. Includes risk level,
     * Black Box Warnings, severe/common effects, monitoring, and
     * dose classification.
     */
    side_effects?: Record<string, SafeRx.SideEffectsData> | undefined;
    interactions?: SafeRx.InteractionsData | undefined;
    /** Pregnancy & lactation risk data keyed by SFX_ID */
    reproductive_safety?: Record<string, SafeRx.ReproductiveSafetyData> | undefined;
    /** Food-drug interaction data keyed by SFX_ID */
    food?: Record<string, SafeRx.FoodData> | undefined;
    clinical?: SafeRx.ClinicalData | undefined;
    /** Maximum daily dose data keyed by SFX_ID */
    dosing?: Record<string, SafeRx.DosingData> | undefined;
}
