// This file was auto-generated by Fern from our API Definition.

import type * as SafeRx from "../index.js";

export interface SideEffectsData {
    /**
     * Overall adverse effect risk level.
     * - `HIGH` — has a Black Box Warning
     * - `MODERATE` — more than 5 severe effects
     * - `LOW` — 5 or fewer severe effects, no BBW
     */
    risk_level?: SideEffectsData.RiskLevel | undefined;
    /** Whether this drug has an FDA Black Box Warning */
    has_black_box_warning?: boolean | undefined;
    /** Black Box Warning details, or null if none exists */
    black_box_warning?: (SafeRx.BlackBoxWarning | null) | undefined;
    /** Total number of known adverse effects */
    total_count?: number | undefined;
    /** Number of severe adverse effects */
    severe_total?: number | undefined;
    /** Top 5 most severe adverse effects */
    severe?: SafeRx.AdverseEffect[] | undefined;
    /** Top 5 most common adverse effects */
    common?: SafeRx.AdverseEffect[] | undefined;
    monitoring?: SafeRx.Monitoring | undefined;
    dose_classification?: SafeRx.DoseClassification | undefined;
}

export namespace SideEffectsData {
    /**
     * Overall adverse effect risk level.
     * - `HIGH` — has a Black Box Warning
     * - `MODERATE` — more than 5 severe effects
     * - `LOW` — 5 or fewer severe effects, no BBW
     */
    export const RiskLevel = {
        Low: "LOW",
        Moderate: "MODERATE",
        High: "HIGH",
    } as const;
    export type RiskLevel = (typeof RiskLevel)[keyof typeof RiskLevel];
}
