# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_drug_safety_health_response_checks_value import GetDrugSafetyHealthResponseChecksValue
from .get_drug_safety_health_response_status import GetDrugSafetyHealthResponseStatus


class GetDrugSafetyHealthResponse(UniversalBaseModel):
    status: typing.Optional[GetDrugSafetyHealthResponseStatus] = None
    subsystem: typing.Optional[str] = None
    checks: typing.Optional[typing.Dict[str, GetDrugSafetyHealthResponseChecksValue]] = None
    latency_ms: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
