// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "developer@example.com"
 *     }
 */
export interface CreateFreeKeyDevelopersRequest {
    /** Your email address */
    email: string;
}
