// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "developer@example.com",
 *         code: "123456"
 *     }
 */
export interface VerifyFreeKeyDevelopersRequest {
    /** The email you used in step 1 */
    email: string;
    /** 6-digit verification code from email */
    code: string;
}
