#!/usr/bin/env python3
"""Generate SafeRx Enterprise SDK source artifacts.

The generator emits small transport clients from the checked-in public Enterprise
OpenAPI projection. Operation metadata and signed-request behavior stay aligned
with that projection.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "packages"
OPENAPI = ROOT / "openapi/enterprise-v1.yaml"
POLICY = ROOT / "openapi/enterprise-v1.yaml"
SECURITY = ROOT / "openapi/components.yaml"
ATTRIBUTION = ROOT / "openapi/enterprise-v1.yaml"
CONSTANTS = ROOT / "openapi/enterprise-v1.yaml"
RELEASE_MANIFEST = ROOT / "release/current.yaml"
MARKER = "AUTO-GENERATED by tools/generate_enterprise_sdks.py"

# Post-MIS-era release line is v2.0.0+ (see RELEASE_CHECKLIST.md / release/current.yaml).
# Pre-MIS 0.x/rc candidate versions must not reappear in generated artifacts.
SDK_VERSION = "2.0.2-preview.1"
PYTHON_PACKAGE_VERSION = "2.0.2rc1"
PKG_DOCS_URL = "https://docs.saferx.online"


def load(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a mapping")
    return value


def operations() -> list[dict[str, Any]]:
    document = load(OPENAPI)
    result: list[dict[str, Any]] = []
    for path, item in document.get("paths", {}).items():
        for method, operation in item.items():
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            if operation.get("x-status", "available") != "available":
                continue
            result.append(
                {
                    "operation_id": operation["operationId"],
                    "method": method.upper(),
                    "path": path,
                    "idempotency_required": bool(operation.get("x-idempotency-required", False)),
                }
            )
    return sorted(result, key=lambda value: value["operation_id"])


def contract_values() -> tuple[int, float, float, str, str, str, str]:
    return (3, 0.1, 2.0, "X-SafeRx-API-Key", "X-SafeRx-Timestamp", "X-SafeRx-Nonce", "X-SafeRx-Signature")


def write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")


def py_operations(ops: list[dict[str, Any]]) -> str:
    lines = []
    for op in ops:
        lines.append(
            f"    {op['operation_id']!r}: Operation({op['operation_id']!r}, {op['method']!r}, "
            f"{op['path']!r}, {op['idempotency_required']!r}),"
        )
    return "\n".join(lines)


def python_client(ops: list[dict[str, Any]], retry: tuple[int, float, float, str, str, str, str]) -> str:
    max_attempts, backoff, backoff_max, key_header, timestamp_header, nonce_header, signature_header = retry
    return f'''# {MARKER}
"""SafeRx Enterprise Python SDK release candidate.

Generated operation metadata is sourced from ``openapi/enterprise-v1.yaml``.
This client does not authenticate from client attribution labels; those labels
are bounded, non-authoritative usage dimensions only.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import secrets
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlsplit
from urllib.request import Request, urlopen


MAX_ATTEMPTS = {max_attempts}
RETRY_BACKOFF_BASE_SECONDS = {backoff!r}
RETRY_BACKOFF_MAX_SECONDS = {backoff_max!r}
CLIENT_KIND = "python_sdk"
SDK_LANGUAGE = "python"
SDK_VERSION = "{SDK_VERSION}"


@dataclass(frozen=True)
class Operation:
    operation_id: str
    method: str
    path: str
    idempotency_required: bool


OPERATIONS = {{
{py_operations(ops)}
}}


class SafeRxProblemDetailsError(RuntimeError):
    """RFC 9457 error with bounded response metadata and safe retry advice."""

    def __init__(self, status: int, problem: dict[str, Any], request_id: str | None = None):
        self.status = status
        self.problem = problem
        self.request_id = request_id or problem.get("request_id")
        self.retry_after = problem.get("retry_after")
        super().__init__(problem.get("detail") or problem.get("title") or "Enterprise request failed")


def canonical_query(query: dict[str, Any] | None) -> str:
    if not query:
        return ""
    pairs: list[tuple[str, str]] = []
    for key, value in query.items():
        values = value if isinstance(value, (list, tuple)) else [value]
        pairs.extend((str(key), str(item)) for item in values)
    return "&".join(
        f"{{quote(key, safe='-._~')}}={{quote(value, safe='-._~')}}"
        for key, value in sorted(pairs)
    )


def canonical_request(method: str, path: str, query: str, body_sha256: str, timestamp: str, nonce: str) -> str:
    return "\\n".join((method.upper(), quote(path, safe="/-._~"), query, body_sha256, timestamp, nonce))


def sign_request(api_key: str, method: str, path: str, query: str, body: bytes, timestamp: str, nonce: str) -> str:
    body_hash = hashlib.sha256(body).hexdigest()
    payload = canonical_request(method, path, query, body_hash, timestamp, nonce)
    digest = hmac.new(api_key.encode("utf-8"), payload.encode("utf-8"), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


class MultipartFile:
    """A file to attach to a multipart/form-data request."""

    __slots__ = ("filename", "content", "content_type")

    def __init__(self, filename: str, content: bytes, content_type: str = "application/octet-stream"):
        self.filename = filename
        self.content = content
        self.content_type = content_type


def encode_multipart(fields: dict[str, Any]) -> tuple[bytes, str]:
    """Build a multipart/form-data body. Signing always covers these exact bytes --
    the same raw-bytes-over-the-wire rule the gateway applies to every content type."""
    boundary = f"----saferx-{{secrets.token_hex(16)}}"
    parts: list[bytes] = []
    for name, value in fields.items():
        if isinstance(value, MultipartFile):
            header = (
                f'--{{boundary}}\\r\\nContent-Disposition: form-data; name="{{name}}"; '
                f'filename="{{value.filename}}"\\r\\nContent-Type: {{value.content_type}}\\r\\n\\r\\n'
            )
            parts.append(header.encode("utf-8") + value.content + b"\\r\\n")
        else:
            header = f'--{{boundary}}\\r\\nContent-Disposition: form-data; name="{{name}}"\\r\\n\\r\\n'
            parts.append(header.encode("utf-8") + str(value).encode("utf-8") + b"\\r\\n")
    parts.append(f"--{{boundary}}--\\r\\n".encode("utf-8"))
    return b"".join(parts), f"multipart/form-data; boundary={{boundary}}"


RETRY_AFTER_MAX_SECONDS = 60.0


def _retry_delay(retry_after: str | None, attempt: int) -> float:
    backoff = min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * (2**attempt))
    if not retry_after:
        return backoff
    try:
        # A server-specified Retry-After is authoritative and may legitimately exceed
        # our internal transient-failure backoff ceiling; bound it only against a
        # separate, larger sanity limit so a real rate-limit wait is honored.
        return min(RETRY_AFTER_MAX_SECONDS, max(backoff, float(retry_after)))
    except ValueError:
        return backoff


class SafeRxClient:
    def __init__(self, base_url: str, api_key: str, *, client_name: str = "saferx-pharma", timeout: float = 30.0):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.client_name = client_name
        self.timeout = timeout

    def request(
        self,
        operation_id: str,
        *,
        query: dict[str, Any] | None = None,
        body: Any = None,
        multipart: dict[str, Any] | None = None,
        path_params: dict[str, Any] | None = None,
        idempotency_key: str | None = None,
    ) -> Any:
        if body is not None and multipart is not None:
            raise ValueError("pass either body or multipart, not both")
        operation = OPERATIONS[operation_id]
        path = operation.path
        for name, value in (path_params or {{}}).items():
            path = path.replace("{{" + name + "}}", quote(str(value), safe="-._~"))
        content_type: str | None = None
        if multipart is not None:
            body_bytes, content_type = encode_multipart(multipart)
        elif body is not None:
            body_bytes = json.dumps(body, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode()
            content_type = "application/json"
        else:
            body_bytes = b""
        canonical_q = canonical_query(query)
        target = f"{{self.base_url}}{{path}}{{('?' + canonical_q) if canonical_q else ''}}"
        request_id = secrets.token_hex(16)
        timestamp = datetime.now(UTC).isoformat(timespec="seconds")
        nonce = secrets.token_urlsafe(24)
        signing_path = urlsplit(self.base_url).path.rstrip("/") + path
        headers = {{
            "Accept": "application/json",
            "{key_header}": self.api_key,
            "{timestamp_header}": timestamp,
            "{nonce_header}": nonce,
            "{signature_header}": sign_request(self.api_key, operation.method, signing_path, canonical_q, body_bytes, timestamp, nonce),
            "X-Request-ID": request_id,
            "X-SafeRx-Client-Kind": CLIENT_KIND,
            "X-SafeRx-Client-Name": self.client_name,
            "X-SafeRx-Client-Version": SDK_VERSION,
            "X-SafeRx-SDK-Language": SDK_LANGUAGE,
            "X-SafeRx-SDK-Version": SDK_VERSION,
        }}
        if content_type is not None:
            headers["Content-Type"] = content_type
        if operation.idempotency_required and not idempotency_key:
            raise ValueError(f"{{operation_id}} requires idempotency_key")
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        request = Request(target, data=body_bytes or None, headers=headers, method=operation.method)
        for attempt in range(MAX_ATTEMPTS):
            try:
                with urlopen(request, timeout=self.timeout) as response:
                    raw = response.read()
                    return json.loads(raw) if raw else None
            except HTTPError as error:
                raw = error.read()
                problem = json.loads(raw) if raw else {{"status": error.code, "title": "REQUEST_FAILED"}}
                if error.code in {{429, 502, 503, 504}} and attempt + 1 < MAX_ATTEMPTS:
                    time.sleep(_retry_delay(error.headers.get("Retry-After") if error.headers else None, attempt))
                    continue
                raise SafeRxProblemDetailsError(error.code, problem, request_id) from error
            except (TimeoutError, URLError) as error:
                if attempt + 1 < MAX_ATTEMPTS:
                    time.sleep(min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * (2**attempt)))
                    continue
                raise SafeRxProblemDetailsError(503, {{"status": 503, "title": "UPSTREAM_UNAVAILABLE", "safe_to_retry": True}}, request_id) from error
        raise AssertionError("retry loop exhausted")


def _operation_method(operation: str):
    def call(self: SafeRxClient, **kwargs: Any) -> Any:
        return self.request(operation, **kwargs)
    call.__name__ = operation
    return call


for _operation_id in OPERATIONS:
    setattr(SafeRxClient, _operation_id, _operation_method(_operation_id))
'''


def ts_operations(ops: list[dict[str, Any]]) -> str:
    return "\n".join(
        f"  {op['operation_id']}: {{ operationId: {op['operation_id']!r}, method: {op['method']!r}, path: {op['path']!r}, idempotencyRequired: {str(op['idempotency_required']).lower()} }},"
        for op in ops
    )


def typescript_client(ops: list[dict[str, Any]], retry: tuple[int, float, float, str, str, str, str]) -> str:
    max_attempts, backoff, backoff_max, key_header, timestamp_header, nonce_header, signature_header = retry
    return f'''// {MARKER}
export type JsonObject = Record<string, unknown>;
export type EnterpriseOperation = {{
  operationId: string; method: string; path: string; idempotencyRequired: boolean;
}};

export const SDK_VERSION = "{SDK_VERSION}";
export const CLIENT_KIND = "typescript_sdk";
export const SDK_LANGUAGE = "typescript";
export const MAX_ATTEMPTS = {max_attempts};
export const RETRY_BACKOFF_BASE_SECONDS = {backoff};
export const RETRY_BACKOFF_MAX_SECONDS = {backoff_max};
export const OPERATIONS: Record<string, EnterpriseOperation> = {{
{ts_operations(ops)}
}};

export type MultipartFile = {{ filename: string; content: Uint8Array; contentType?: string }};
export type RequestOptions = {{ query?: Record<string, string | number | boolean | (string | number | boolean)[]>; body?: unknown; multipart?: Record<string, string | MultipartFile>; pathParams?: Record<string, string | number>; idempotencyKey?: string; signal?: AbortSignal; }};

export class SafeRxProblemDetailsError extends Error {{
  readonly status: number; readonly problem: JsonObject; readonly requestId?: string;
  constructor(status: number, problem: JsonObject, requestId?: string) {{
    super(String(problem.detail ?? problem.title ?? "Enterprise request failed"));
    this.name = "SafeRxProblemDetailsError"; this.status = status; this.problem = problem; this.requestId = requestId ?? (String(problem.request_id ?? "") || undefined);
  }}
}}

function encode(value: string): string {{ return encodeURIComponent(value).replace(/[!'()*]/g, (char) => `%${{char.charCodeAt(0).toString(16).toUpperCase()}}`); }}
export function canonicalQuery(query: RequestOptions["query"]): string {{
  if (!query) return "";
  const pairs: string[] = [];
  for (const [key, raw] of Object.entries(query)) for (const value of Array.isArray(raw) ? raw : [raw]) pairs.push(`${{encode(key)}}=${{encode(String(value))}}`);
  return pairs.sort().join("&");
}}
function canonicalJson(value: unknown): string {{
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${{value.map(canonicalJson).join(",")}}]`;
  return `{{${{Object.entries(value as JsonObject).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${{JSON.stringify(key)}}:${{canonicalJson(item)}}`).join(",")}}}}`;
}}
function bytes(value: string): Uint8Array {{ return new TextEncoder().encode(value) as Uint8Array; }}
async function sha256(value: Uint8Array): Promise<string> {{ const digest = await crypto.subtle.digest("SHA-256", value as BufferSource); return [...new Uint8Array(digest)].map((item) => item.toString(16).padStart(2, "0")).join(""); }}
async function hmac(key: string, value: string): Promise<string> {{ const cryptoKey = await crypto.subtle.importKey("raw", bytes(key) as BufferSource, {{ name: "HMAC", hash: "SHA-256" }}, false, ["sign"]); const digest = await crypto.subtle.sign("HMAC", cryptoKey, bytes(value) as BufferSource); return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/=+$/, "").replace(/\\+/g, "-").replace(/\\//g, "_"); }}
export function canonicalRequest(method: string, path: string, query: string, bodyHash: string, timestamp: string, nonce: string): string {{ return [method.toUpperCase(), encode(path).replace(/%2F/g, "/"), query, bodyHash, timestamp, nonce].join("\\n"); }}
const RETRY_AFTER_MAX_SECONDS = 60;
function retryDelaySeconds(retryAfter: string | null, attempt: number): number {{
  const backoff = Math.min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * 2 ** attempt);
  if (!retryAfter) return backoff;
  const parsed = Number(retryAfter);
  if (!Number.isFinite(parsed)) return backoff;
  return Math.min(RETRY_AFTER_MAX_SECONDS, Math.max(backoff, parsed));
}}

function isMultipartFile(value: string | MultipartFile): value is MultipartFile {{ return typeof value === "object" && value !== null && "content" in value; }}
export function encodeMultipart(fields: Record<string, string | MultipartFile>): {{ body: Uint8Array; contentType: string }} {{
  const boundary = `----saferx-${{crypto.randomUUID().replace(/-/g, "")}}`;
  const chunks: Uint8Array[] = [];
  for (const [name, value] of Object.entries(fields)) {{
    if (isMultipartFile(value)) {{
      chunks.push(bytes(`--${{boundary}}\\r\\nContent-Disposition: form-data; name="${{name}}"; filename="${{value.filename}}"\\r\\nContent-Type: ${{value.contentType ?? "application/octet-stream"}}\\r\\n\\r\\n`));
      chunks.push(value.content);
      chunks.push(bytes("\\r\\n"));
    }} else {{
      chunks.push(bytes(`--${{boundary}}\\r\\nContent-Disposition: form-data; name="${{name}}"\\r\\n\\r\\n${{value}}\\r\\n`));
    }}
  }}
  chunks.push(bytes(`--${{boundary}}--\\r\\n`));
  const total = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
  const body = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {{ body.set(chunk, offset); offset += chunk.length; }}
  return {{ body, contentType: `multipart/form-data; boundary=${{boundary}}` }};
}}

export class SafeRxClient {{
  constructor(private readonly baseUrl: string, private readonly apiKey: string, private readonly clientName = "saferx-pharma-sdk", private readonly fetchImpl: typeof fetch = fetch) {{}}
  async request(operationId: string, options: RequestOptions = {{}}): Promise<unknown> {{
    const operation = OPERATIONS[operationId]; if (!operation) throw new Error(`Unknown Enterprise operation: ${{operationId}}`);
    let path = operation.path; for (const [key, value] of Object.entries(options.pathParams ?? {{}})) path = path.replace(`{{${{key}}}}`, encode(String(value)));
    if (operation.idempotencyRequired && !options.idempotencyKey) throw new Error(`${{operationId}} requires idempotencyKey`);
    if (options.body !== undefined && options.multipart !== undefined) throw new Error("pass either body or multipart, not both");
    let bodyBytes: Uint8Array; let contentType: string | undefined; let sendBody: Uint8Array | string | undefined;
    if (options.multipart !== undefined) {{
      const encoded = encodeMultipart(options.multipart); bodyBytes = encoded.body; contentType = encoded.contentType; sendBody = encoded.body;
    }} else if (options.body !== undefined) {{
      const json = canonicalJson(options.body); bodyBytes = bytes(json); contentType = "application/json"; sendBody = json;
    }} else {{
      bodyBytes = bytes(""); sendBody = undefined;
    }}
    const query = canonicalQuery(options.query);
    const timestamp = new Date().toISOString(); const nonce = crypto.randomUUID(); const requestId = crypto.randomUUID();
    const signingPath = new URL(this.baseUrl).pathname.replace(/\\/+$/, "") + path;
    const signature = await hmac(this.apiKey, canonicalRequest(operation.method, signingPath, query, await sha256(bodyBytes), timestamp, nonce));
    const headers: Record<string, string> = {{ Accept: "application/json", "{key_header}": this.apiKey, "{timestamp_header}": timestamp, "{nonce_header}": nonce, "{signature_header}": signature, "X-Request-ID": requestId, "X-SafeRx-Client-Kind": CLIENT_KIND, "X-SafeRx-Client-Name": this.clientName, "X-SafeRx-Client-Version": SDK_VERSION, "X-SafeRx-SDK-Language": SDK_LANGUAGE, "X-SafeRx-SDK-Version": SDK_VERSION }};
    if (contentType !== undefined) headers["Content-Type"] = contentType; if (options.idempotencyKey) headers["Idempotency-Key"] = options.idempotencyKey;
    const target = `${{this.baseUrl.replace(/\\/+$/, "")}}${{path}}${{query ? `?${{query}}` : ""}}`;
    for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {{
      try {{ const response = await this.fetchImpl(target, {{ method: operation.method, headers, body: sendBody as BodyInit | undefined, signal: options.signal }}); const raw = await response.text(); const parsed = raw ? JSON.parse(raw) : undefined;
        if (response.ok) return parsed; if ([429, 502, 503, 504].includes(response.status) && attempt + 1 < MAX_ATTEMPTS) {{ await new Promise((resolve) => setTimeout(resolve, retryDelaySeconds(response.headers.get("Retry-After"), attempt) * 1000)); continue; }}
        throw new SafeRxProblemDetailsError(response.status, (parsed ?? {{ status: response.status, title: "REQUEST_FAILED" }}) as JsonObject, requestId);
      }} catch (error) {{ if (error instanceof SafeRxProblemDetailsError) throw error; if (attempt + 1 >= MAX_ATTEMPTS) throw new SafeRxProblemDetailsError(503, {{ status: 503, title: "UPSTREAM_UNAVAILABLE", safe_to_retry: true }}, requestId); await new Promise((resolve) => setTimeout(resolve, Math.min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * 2 ** attempt) * 1000)); }}
    }}
    throw new Error("retry loop exhausted");
  }}
}}
'''


def csharp_operations(ops: list[dict[str, Any]]) -> str:
    return "\n".join(
        f'        ["{op["operation_id"]}"] = new EnterpriseOperation("{op["operation_id"]}", HttpMethod.{op["method"].title()}, "{op["path"]}", {str(op["idempotency_required"]).lower()}),'
        for op in ops
    )


def csharp_client(ops: list[dict[str, Any]], retry: tuple[int, float, float, str, str, str, str]) -> str:
    max_attempts, backoff, backoff_max, key_header, timestamp_header, nonce_header, signature_header = retry
    return f'''// {MARKER}
using System.Net;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace SafeRx;

public sealed record EnterpriseOperation(string OperationId, HttpMethod Method, string Path, bool IdempotencyRequired);

public sealed record MultipartFilePart(string FileName, byte[] Content, string ContentType = "application/octet-stream");

public static class MultipartEncoder
{{
    public static (byte[] Body, string ContentType) Encode(IReadOnlyDictionary<string, object> fields)
    {{
        var boundary = "----saferx-" + Guid.NewGuid().ToString("N");
        using var stream = new MemoryStream();
        void WriteAscii(string text) {{ var bytes = Encoding.UTF8.GetBytes(text); stream.Write(bytes, 0, bytes.Length); }}
        foreach (var (name, value) in fields)
        {{
            if (value is MultipartFilePart file)
            {{
                WriteAscii($"--{{boundary}}\\r\\nContent-Disposition: form-data; name=\\"{{name}}\\"; filename=\\"{{file.FileName}}\\"\\r\\nContent-Type: {{file.ContentType}}\\r\\n\\r\\n");
                stream.Write(file.Content, 0, file.Content.Length);
                WriteAscii("\\r\\n");
            }}
            else
            {{
                WriteAscii($"--{{boundary}}\\r\\nContent-Disposition: form-data; name=\\"{{name}}\\"\\r\\n\\r\\n{{value}}\\r\\n");
            }}
        }}
        WriteAscii($"--{{boundary}}--\\r\\n");
        return (stream.ToArray(), $"multipart/form-data; boundary={{boundary}}");
    }}
}}

public sealed class SafeRxProblemDetailsException : Exception
{{
    public HttpStatusCode StatusCode {{ get; }}
    public JsonElement Problem {{ get; }}
    public SafeRxProblemDetailsException(HttpStatusCode statusCode, JsonElement problem) : base(problem.ValueKind == JsonValueKind.Object && problem.TryGetProperty("detail", out var detail) ? detail.GetString() : "Enterprise request failed") {{ StatusCode = statusCode; Problem = problem; }}
}}

public sealed class SafeRxClient
{{
    public const string SdkVersion = "{SDK_VERSION}";
    public static readonly IReadOnlyDictionary<string, EnterpriseOperation> Operations = new Dictionary<string, EnterpriseOperation>
    {{
{csharp_operations(ops)}
    }};
    private const int MaxAttempts = {max_attempts};
    private const double RetryBackoffBaseSeconds = {backoff};
    private const double RetryBackoffMaxSeconds = {backoff_max};
    private const double RetryAfterMaxSeconds = 60.0;
    private readonly HttpClient _http; private readonly Uri _baseUrl; private readonly string _apiKey; private readonly string _clientName;
    public SafeRxClient(HttpClient http, Uri baseUrl, string apiKey, string clientName = "SafeRx") {{ _http = http; _baseUrl = baseUrl; _apiKey = apiKey; _clientName = clientName; }}

    private static double RetryDelaySeconds(RetryConditionHeaderValue? retryAfter, int attempt)
    {{
        var backoff = Math.Min(RetryBackoffMaxSeconds, RetryBackoffBaseSeconds * Math.Pow(2, attempt));
        if (retryAfter?.Delta is TimeSpan delta) return Math.Min(RetryAfterMaxSeconds, Math.Max(backoff, delta.TotalSeconds));
        if (retryAfter?.Date is DateTimeOffset date) return Math.Min(RetryAfterMaxSeconds, Math.Max(backoff, (date - DateTimeOffset.UtcNow).TotalSeconds));
        return backoff;
    }}

    public async Task<JsonElement> RequestAsync(string operationId, object? body = null, IReadOnlyDictionary<string, object>? multipart = null, IReadOnlyDictionary<string, string>? pathParams = null, string? idempotencyKey = null, CancellationToken cancellationToken = default)
    {{
        if (!Operations.TryGetValue(operationId, out var operation)) throw new ArgumentException("Unknown Enterprise operation", nameof(operationId));
        if (body is not null && multipart is not null) throw new ArgumentException("pass either body or multipart, not both");
        var path = operation.Path; foreach (var pair in pathParams ?? new Dictionary<string, string>()) path = path.Replace("{{" + pair.Key + "}}", Uri.EscapeDataString(pair.Value), StringComparison.Ordinal);
        if (operation.IdempotencyRequired && string.IsNullOrWhiteSpace(idempotencyKey)) throw new ArgumentException("Operation requires idempotencyKey", nameof(idempotencyKey));
        byte[] bytes; string json = ""; string? contentType = null;
        if (multipart is not null) {{ (bytes, contentType) = MultipartEncoder.Encode(multipart); }}
        else if (body is not null) {{ json = JsonSerializer.Serialize(body, new JsonSerializerOptions {{ PropertyNamingPolicy = JsonNamingPolicy.CamelCase }}); bytes = Encoding.UTF8.GetBytes(json); contentType = "application/json"; }}
        else {{ bytes = Array.Empty<byte>(); }}
        var requestId = Guid.NewGuid().ToString();
        var bodyHash = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
        for (var attempt = 0; attempt < MaxAttempts; attempt++) {{
            var timestamp = DateTimeOffset.UtcNow.ToString("O"); var nonce = Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant();
            var signingPath = _baseUrl.AbsolutePath.TrimEnd('/') + path;
            var canonical = string.Join("\\n", operation.Method.Method.ToUpperInvariant(), signingPath, "", bodyHash, timestamp, nonce);
            using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(_apiKey)); var signature = Convert.ToBase64String(hmac.ComputeHash(Encoding.UTF8.GetBytes(canonical))).TrimEnd('=').Replace('+', '-').Replace('/', '_');
            var requestUri = new Uri(new Uri(_baseUrl.ToString().TrimEnd('/') + "/"), path.TrimStart('/'));
            using var request = new HttpRequestMessage(operation.Method, requestUri); request.Headers.TryAddWithoutValidation("{key_header}", _apiKey); request.Headers.TryAddWithoutValidation("{timestamp_header}", timestamp); request.Headers.TryAddWithoutValidation("{nonce_header}", nonce); request.Headers.TryAddWithoutValidation("{signature_header}", signature); request.Headers.TryAddWithoutValidation("X-Request-ID", requestId); request.Headers.TryAddWithoutValidation("X-SafeRx-Client-Kind", "csharp_sdk"); request.Headers.TryAddWithoutValidation("X-SafeRx-Client-Name", _clientName); request.Headers.TryAddWithoutValidation("X-SafeRx-Client-Version", SdkVersion); request.Headers.TryAddWithoutValidation("X-SafeRx-SDK-Language", "csharp"); request.Headers.TryAddWithoutValidation("X-SafeRx-SDK-Version", SdkVersion); if (idempotencyKey is not null) request.Headers.TryAddWithoutValidation("Idempotency-Key", idempotencyKey);
            if (multipart is not null) {{ var content = new ByteArrayContent(bytes); content.Headers.ContentType = MediaTypeHeaderValue.Parse(contentType!); request.Content = content; }}
            else if (body is not null) {{ request.Content = new StringContent(json, Encoding.UTF8, "application/json"); }}
            try {{ using var response = await _http.SendAsync(request, cancellationToken); var raw = await response.Content.ReadAsStringAsync(cancellationToken); var parsed = JsonSerializer.Deserialize<JsonElement>(string.IsNullOrWhiteSpace(raw) ? "null" : raw); if (response.IsSuccessStatusCode) return parsed; if (!new[] {{ 429, 502, 503, 504 }}.Contains((int)response.StatusCode) || attempt + 1 >= MaxAttempts) throw new SafeRxProblemDetailsException(response.StatusCode, parsed); await Task.Delay(TimeSpan.FromSeconds(RetryDelaySeconds(response.Headers.RetryAfter, attempt)), cancellationToken); }} catch (SafeRxProblemDetailsException) {{ throw; }} catch (HttpRequestException) when (attempt + 1 < MaxAttempts) {{ await Task.Delay(TimeSpan.FromSeconds(Math.Min(RetryBackoffMaxSeconds, RetryBackoffBaseSeconds * Math.Pow(2, attempt))), cancellationToken); }}
        }}
        throw new InvalidOperationException("retry loop exhausted");
    }}
}}
'''


def generate(verify: bool = False) -> int:
    ops = operations()
    retry = contract_values()
    expected = [op["operation_id"] for op in ops]
    files = {
        OUT / "python/src/saferx_pharma/client.py": python_client(ops, retry),
        OUT / "python/src/saferx_pharma/__init__.py": f'''# {MARKER}\nfrom .client import MultipartFile, OPERATIONS, SafeRxClient, SafeRxProblemDetailsError, canonical_query, canonical_request, encode_multipart, sign_request\n\n__all__ = ["MultipartFile", "OPERATIONS", "SafeRxClient", "SafeRxProblemDetailsError", "canonical_query", "canonical_request", "encode_multipart", "sign_request"]\n''',
        OUT / "typescript/src/client.ts": typescript_client(ops, retry),
        OUT / "csharp/SafeRxClient.cs": csharp_client(ops, retry),
        OUT / "python/pyproject.toml": f'''[build-system]\nrequires = ["setuptools>=68"]\nbuild-backend = "setuptools.build_meta"\n\n[project]\nname = "saferx-pharma"\nversion = "{PYTHON_PACKAGE_VERSION}"\ndescription = "Signed Python client for the SafeRx Enterprise API"\nreadme = "README.md"\nrequires-python = ">=3.11"\nlicense = {{text = "MIT"}}\nauthors = [{{name = "SafeRx"}}]\ndependencies = []\n\n[project.urls]\nHomepage = "https://docs.saferx.online"\nRepository = "https://github.com/KaRamHelal/SafeRx_Pharma"\n''',
        OUT / "python/README.md": f'''# saferx-pharma\n\nSigned Python client for the [SafeRx Enterprise API]({PKG_DOCS_URL}).\n\n```bash\npip install saferx-pharma\n```\n\n```python\nfrom saferx_pharma import SafeRxClient\n\nclient = SafeRxClient(\n    base_url="https://saferx.online/api/enterprise/v1",\n    api_key="YOUR_ENTERPRISE_KEY",\n)\n\nresult = client.enterprise_safety_check(\n    body={{\n        "locale": "en",\n        "medications": [{{"input_text": "Augmentin 1g"}}],\n        "requested_domains": ["ddi"],\n    }},\n    idempotency_key="safety-check-001",\n)\n```\n\nServer-side use only -- this client signs requests with your API key as the\nHMAC secret. Never embed it in browser or client-controlled code.\n\nFull docs: {PKG_DOCS_URL}\n''',
        OUT / "typescript/package.json": f'''{{\n  "name": "saferx-pharma-sdk",\n  "version": "{SDK_VERSION}",\n  "description": "Signed TypeScript client for the SafeRx Enterprise API",\n  "license": "MIT",\n  "homepage": "{PKG_DOCS_URL}",\n  "repository": {{"type": "git", "url": "https://github.com/KaRamHelal/SafeRx_Pharma"}},\n  "private": true,\n  "type": "module",\n  "exports": {{".": "./dist/client.js"}},\n  "scripts": {{"build": "tsc -p tsconfig.json", "test": "node --test dist/client.test.js"}},\n  "devDependencies": {{"typescript": "6.0.3"}}\n}}\n''',
        OUT / "typescript/tsconfig.json": '''{\n  "compilerOptions": {"target": "ES2022", "module": "NodeNext", "moduleResolution": "NodeNext", "strict": true, "declaration": true, "outDir": "dist", "rootDir": "src", "skipLibCheck": true},\n  "include": ["src/**/*.ts"]\n}\n''',
        OUT / "typescript/README.md": f'''# saferx-pharma-sdk\n\nSigned TypeScript client for the [SafeRx Enterprise API]({PKG_DOCS_URL}).\n\n**Server-side use only.** This client signs every request with your API key\nas the HMAC secret -- never import or bundle it into browser or\nclient-controlled code.\n\n```bash\nnpm install saferx-pharma-sdk\n```\n\n```typescript\nimport {{ SafeRxClient }} from "saferx-pharma-sdk";\n\nconst client = new SafeRxClient(\n  "https://saferx.online/api/enterprise/v1",\n  process.env.SAFERX_API_KEY!,\n);\n\nconst result = await client.request("enterprise_safety_check", {{\n  body: {{\n    locale: "en",\n    medications: [{{ input_text: "Augmentin 1g" }}],\n    requested_domains: ["ddi"],\n  }},\n  idempotencyKey: "safety-check-001",\n}});\n```\n\nFull docs: {PKG_DOCS_URL}\n''',
        OUT / "csharp/SafeRx.csproj": f'''<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <TargetFramework>net8.0</TargetFramework>\n    <PackageId>SafeRx</PackageId>\n    <Version>{SDK_VERSION}</Version>\n    <Authors>SafeRx</Authors>\n    <Description>Signing-aware SafeRx Enterprise API preview client.</Description>\n    <PackageTags>saferx;enterprise-api;medication-safety</PackageTags>\n    <PackageLicenseExpression>MIT</PackageLicenseExpression>\n    <PackageProjectUrl>{PKG_DOCS_URL}</PackageProjectUrl>\n    <RepositoryUrl>https://github.com/KaRamHelal/SafeRx_Pharma</RepositoryUrl>\n    <PackageReadmeFile>README.md</PackageReadmeFile>\n    <Nullable>enable</Nullable>\n    <ImplicitUsings>enable</ImplicitUsings>\n    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>\n  </PropertyGroup>\n  <ItemGroup>\n    <None Include="README.md" Pack="true" PackagePath="\\" />\n  </ItemGroup>\n</Project>\n''',
        OUT / "csharp/README.md": f'''# SafeRx\n\nSigned .NET client for the [SafeRx Enterprise API]({PKG_DOCS_URL}).\n\n```xml\n<PackageReference Include="SafeRx" Version="{SDK_VERSION}" />\n```\n\n```csharp\nusing SafeRx;\n\nusing var http = new HttpClient();\nvar client = new SafeRxClient(\n    http,\n    new Uri("https://saferx.online/api/enterprise/v1"),\n    Environment.GetEnvironmentVariable("SAFERX_API_KEY")!\n);\n\nvar result = await client.RequestAsync(\n    "enterprise_safety_check",\n    new {{\n        locale = "en",\n        medications = new[] {{ new {{ input_text = "Augmentin 1g" }} }},\n        requested_domains = new[] {{ "ddi" }}\n    }},\n    idempotencyKey: "safety-check-001"\n);\n```\n\nFull docs: {PKG_DOCS_URL}\n''',
    }
    if verify:
        for path, content in files.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"stale generated SDK artifact: {path.relative_to(ROOT)}")
                return 1
        return 0
    for path, content in files.items():
        write(path, content)
    source_hashes = {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest() for path in (OPENAPI, POLICY, SECURITY, ATTRIBUTION, CONSTANTS)}
    artifact_hashes = {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest() for path in files}
    release = load(RELEASE_MANIFEST)
    manifest = {
        "release_id": release["release_id"],
        "release_status": release["status"],
        "api_contract_version": "enterprise-v1",
        "sdk_version": SDK_VERSION,
        "operation_ids": expected,
        "source_sha256": source_hashes,
        "artifact_sha256": artifact_hashes,
        "generator": "scripts/generate_enterprise_sdks.py",
        "publishable": release["publishable"],
    }
    write(OUT / "release-manifest.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    sbom = {"bomFormat": "CycloneDX", "specVersion": "1.6", "version": 1, "metadata": {"component": {"type": "application", "name": "saferx-enterprise-sdks", "version": SDK_VERSION}}, "components": []}
    write(OUT / "sbom.cdx.json", json.dumps(sbom, indent=2, sort_keys=True) + "\n")
    provenance = {"_type": "https://in-toto.io/Statement/v1", "predicateType": "https://slsa.dev/provenance/v1", "subject": [{"name": name, "digest": {"sha256": digest}} for name, digest in sorted(artifact_hashes.items())], "predicate": {"buildType": "saferx-pharma/enterprise-sdk-generator", "generator": "scripts/generate_enterprise_sdks.py", "materials": [{"uri": name, "digest": {"sha256": digest}} for name, digest in sorted(source_hashes.items())]}}
    write(OUT / "provenance.intoto.json", json.dumps(provenance, indent=2, sort_keys=True) + "\n")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return generate(verify=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
