#!/usr/bin/env python3
"""Render the root CHANGELOG.md into a single Fern docs page.

Replaces the old pattern of one hand-written .mdx file per release date
(fern/docs/pages/changelog/*.mdx, individually wired into fern/docs.yml's
navigation) with one page generated from the single source of truth.
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHANGELOG = ROOT / "CHANGELOG.md"
OUT = ROOT / "fern/docs/pages/changelog.mdx"
MARKER = "AUTO-GENERATED by scripts/render_fern_changelog.py -- do not hand-edit"


def render() -> str:
    body = CHANGELOG.read_text(encoding="utf-8")
    # Drop the top-level "# Changelog" heading; the Fern page supplies its own title.
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
    body = "\n".join(lines).strip() + "\n"
    return f"""---
title: Changelog
subtitle: SafeRx Enterprise release notes
---
{{/* {MARKER} */}}

{body}"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print(f"stale generated changelog page: {OUT.relative_to(ROOT)}")
            return 1
        return 0
    OUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
