// This file was auto-generated by Fern from our API Definition.

import * as SafeRx from "../../src/api/index";
import { SafeRxClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DevelopersClient", () => {
    test("createFreeKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SafeRxClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "developer@example.com" };
        const rawResponseBody = { message: "Verification code sent to your email", email: "developer@example.com" };
        server
            .mockEndpoint()
            .post("/api/developers/keys/free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.developers.createFreeKey({
            email: "developer@example.com",
        });
        expect(response).toEqual({
            message: "Verification code sent to your email",
            email: "developer@example.com",
        });
    });

    test("createFreeKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SafeRxClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/api/developers/keys/free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.developers.createFreeKey({
                email: "email",
            });
        }).rejects.toThrow(SafeRx.TooManyRequestsError);
    });

    test("createFreeKey (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SafeRxClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/api/developers/keys/free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.developers.createFreeKey({
                email: "email",
            });
        }).rejects.toThrow(SafeRx.InternalServerError);
    });

    test("verifyFreeKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SafeRxClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "developer@example.com", code: "123456" };
        const rawResponseBody = {
            api_key: "sfx_free_a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
            tier: "free",
            limits: { requests_per_minute: 20, requests_per_day: 60 },
        };
        server
            .mockEndpoint()
            .post("/api/developers/keys/free/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.developers.verifyFreeKey({
            email: "developer@example.com",
            code: "123456",
        });
        expect(response).toEqual({
            api_key: "sfx_free_a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
            tier: "free",
            limits: {
                requests_per_minute: 20,
                requests_per_day: 60,
            },
        });
    });

    test("verifyFreeKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SafeRxClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email", code: "code" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/api/developers/keys/free/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.developers.verifyFreeKey({
                email: "email",
                code: "code",
            });
        }).rejects.toThrow(SafeRx.BadRequestError);
    });

    test("verifyFreeKey (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SafeRxClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "email", code: "code" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/api/developers/keys/free/verify")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.developers.verifyFreeKey({
                email: "email",
                code: "code",
            });
        }).rejects.toThrow(SafeRx.ForbiddenError);
    });
});
