// AUTO-GENERATED by tools/generate_enterprise_sdks.py
export type JsonObject = Record<string, unknown>;
export type EnterpriseOperation = {
  operationId: string; method: string; path: string; idempotencyRequired: boolean;
};

export const SDK_VERSION = "2.0.2";
export const CLIENT_KIND = "typescript_sdk";
export const SDK_LANGUAGE = "typescript";
export const MAX_ATTEMPTS = 3;
export const RETRY_BACKOFF_BASE_SECONDS = 0.1;
export const RETRY_BACKOFF_MAX_SECONDS = 2.0;
export const OPERATIONS: Record<string, EnterpriseOperation> = {
  enterprise_erx_safety_check: { operationId: 'enterprise_erx_safety_check', method: 'POST', path: '/erx/safety-checks', idempotencyRequired: true },
  enterprise_ocr_prescription_create: { operationId: 'enterprise_ocr_prescription_create', method: 'POST', path: '/ocr/prescriptions', idempotencyRequired: true },
  enterprise_ocr_prescription_events: { operationId: 'enterprise_ocr_prescription_events', method: 'GET', path: '/ocr/prescriptions/{prescription_id}/events', idempotencyRequired: false },
  enterprise_ocr_prescription_read: { operationId: 'enterprise_ocr_prescription_read', method: 'GET', path: '/ocr/prescriptions/{prescription_id}', idempotencyRequired: false },
  enterprise_ocr_prescription_resolve: { operationId: 'enterprise_ocr_prescription_resolve', method: 'POST', path: '/ocr/prescriptions/{prescription_id}/medications/resolve', idempotencyRequired: false },
  enterprise_ocr_prescription_review: { operationId: 'enterprise_ocr_prescription_review', method: 'POST', path: '/ocr/prescriptions/{prescription_id}/review', idempotencyRequired: false },
  enterprise_ocr_prescription_safety: { operationId: 'enterprise_ocr_prescription_safety', method: 'POST', path: '/ocr/prescriptions/{prescription_id}/safety-checks', idempotencyRequired: false },
  enterprise_registry_autocomplete: { operationId: 'enterprise_registry_autocomplete', method: 'GET', path: '/registry/suggest', idempotencyRequired: false },
  enterprise_registry_ingredients: { operationId: 'enterprise_registry_ingredients', method: 'GET', path: '/registry/ingredients', idempotencyRequired: false },
  enterprise_registry_product_detail: { operationId: 'enterprise_registry_product_detail', method: 'GET', path: '/registry/products/{sfrx_id}', idempotencyRequired: false },
  enterprise_registry_resolve: { operationId: 'enterprise_registry_resolve', method: 'POST', path: '/registry/resolve', idempotencyRequired: false },
  enterprise_registry_search: { operationId: 'enterprise_registry_search', method: 'GET', path: '/registry/search', idempotencyRequired: false },
  enterprise_safety_capabilities: { operationId: 'enterprise_safety_capabilities', method: 'GET', path: '/safety/capabilities', idempotencyRequired: false },
  enterprise_safety_check: { operationId: 'enterprise_safety_check', method: 'POST', path: '/safety/checks', idempotencyRequired: true },
};

export type MultipartFile = { filename: string; content: Uint8Array; contentType?: string };
export type RequestOptions = { query?: Record<string, string | number | boolean | (string | number | boolean)[]>; body?: unknown; multipart?: Record<string, string | MultipartFile>; pathParams?: Record<string, string | number>; idempotencyKey?: string; signal?: AbortSignal; };

export class SafeRxProblemDetailsError extends Error {
  readonly status: number; readonly problem: JsonObject; readonly requestId?: string;
  constructor(status: number, problem: JsonObject, requestId?: string) {
    super(String(problem.detail ?? problem.title ?? "Enterprise request failed"));
    this.name = "SafeRxProblemDetailsError"; this.status = status; this.problem = problem; this.requestId = requestId ?? (String(problem.request_id ?? "") || undefined);
  }
}

function encode(value: string): string { return encodeURIComponent(value).replace(/[!'()*]/g, (char) => `%${char.charCodeAt(0).toString(16).toUpperCase()}`); }
export function canonicalQuery(query: RequestOptions["query"]): string {
  if (!query) return "";
  const pairs: string[] = [];
  for (const [key, raw] of Object.entries(query)) for (const value of Array.isArray(raw) ? raw : [raw]) pairs.push(`${encode(key)}=${encode(String(value))}`);
  return pairs.sort().join("&");
}
function canonicalJson(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  return `{${Object.entries(value as JsonObject).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`).join(",")}}`;
}
function bytes(value: string): Uint8Array { return new TextEncoder().encode(value) as Uint8Array; }
async function sha256(value: Uint8Array): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", value as BufferSource); return [...new Uint8Array(digest)].map((item) => item.toString(16).padStart(2, "0")).join(""); }
async function hmac(key: string, value: string): Promise<string> { const cryptoKey = await crypto.subtle.importKey("raw", bytes(key) as BufferSource, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const digest = await crypto.subtle.sign("HMAC", cryptoKey, bytes(value) as BufferSource); return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_"); }
export function canonicalRequest(method: string, path: string, query: string, bodyHash: string, timestamp: string, nonce: string): string { return [method.toUpperCase(), encode(path).replace(/%2F/g, "/"), query, bodyHash, timestamp, nonce].join("\n"); }
const RETRY_AFTER_MAX_SECONDS = 60;
function retryDelaySeconds(retryAfter: string | null, attempt: number): number {
  const backoff = Math.min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * 2 ** attempt);
  if (!retryAfter) return backoff;
  const parsed = Number(retryAfter);
  if (!Number.isFinite(parsed)) return backoff;
  return Math.min(RETRY_AFTER_MAX_SECONDS, Math.max(backoff, parsed));
}

function isMultipartFile(value: string | MultipartFile): value is MultipartFile { return typeof value === "object" && value !== null && "content" in value; }
export function encodeMultipart(fields: Record<string, string | MultipartFile>): { body: Uint8Array; contentType: string } {
  const boundary = `----saferx-${crypto.randomUUID().replace(/-/g, "")}`;
  const chunks: Uint8Array[] = [];
  for (const [name, value] of Object.entries(fields)) {
    if (isMultipartFile(value)) {
      chunks.push(bytes(`--${boundary}\r\nContent-Disposition: form-data; name="${name}"; filename="${value.filename}"\r\nContent-Type: ${value.contentType ?? "application/octet-stream"}\r\n\r\n`));
      chunks.push(value.content);
      chunks.push(bytes("\r\n"));
    } else {
      chunks.push(bytes(`--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\n\r\n${value}\r\n`));
    }
  }
  chunks.push(bytes(`--${boundary}--\r\n`));
  const total = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
  const body = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) { body.set(chunk, offset); offset += chunk.length; }
  return { body, contentType: `multipart/form-data; boundary=${boundary}` };
}

export class SafeRxClient {
  constructor(private readonly baseUrl: string, private readonly apiKey: string, private readonly clientName = "saferx-pharma-sdk", private readonly fetchImpl: typeof fetch = fetch) {}
  async request(operationId: string, options: RequestOptions = {}): Promise<unknown> {
    const operation = OPERATIONS[operationId]; if (!operation) throw new Error(`Unknown Enterprise operation: ${operationId}`);
    let path = operation.path; for (const [key, value] of Object.entries(options.pathParams ?? {})) path = path.replace(`{${key}}`, encode(String(value)));
    if (operation.idempotencyRequired && !options.idempotencyKey) throw new Error(`${operationId} requires idempotencyKey`);
    if (options.body !== undefined && options.multipart !== undefined) throw new Error("pass either body or multipart, not both");
    let bodyBytes: Uint8Array; let contentType: string | undefined; let sendBody: Uint8Array | string | undefined;
    if (options.multipart !== undefined) {
      const encoded = encodeMultipart(options.multipart); bodyBytes = encoded.body; contentType = encoded.contentType; sendBody = encoded.body;
    } else if (options.body !== undefined) {
      const json = canonicalJson(options.body); bodyBytes = bytes(json); contentType = "application/json"; sendBody = json;
    } else {
      bodyBytes = bytes(""); sendBody = undefined;
    }
    const query = canonicalQuery(options.query);
    const timestamp = new Date().toISOString(); const nonce = crypto.randomUUID(); const requestId = crypto.randomUUID();
    const signingPath = new URL(this.baseUrl).pathname.replace(/\/+$/, "") + path;
    const signature = await hmac(this.apiKey, canonicalRequest(operation.method, signingPath, query, await sha256(bodyBytes), timestamp, nonce));
    const headers: Record<string, string> = { Accept: "application/json", "X-SafeRx-API-Key": this.apiKey, "X-SafeRx-Timestamp": timestamp, "X-SafeRx-Nonce": nonce, "X-SafeRx-Signature": signature, "X-Request-ID": requestId, "X-SafeRx-Client-Kind": CLIENT_KIND, "X-SafeRx-Client-Name": this.clientName, "X-SafeRx-Client-Version": SDK_VERSION, "X-SafeRx-SDK-Language": SDK_LANGUAGE, "X-SafeRx-SDK-Version": SDK_VERSION };
    if (contentType !== undefined) headers["Content-Type"] = contentType; if (options.idempotencyKey) headers["Idempotency-Key"] = options.idempotencyKey;
    const target = `${this.baseUrl.replace(/\/+$/, "")}${path}${query ? `?${query}` : ""}`;
    for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
      try { const response = await this.fetchImpl(target, { method: operation.method, headers, body: sendBody as BodyInit | undefined, signal: options.signal }); const raw = await response.text(); const parsed = raw ? JSON.parse(raw) : undefined;
        if (response.ok) return parsed; if ([429, 502, 503, 504].includes(response.status) && attempt + 1 < MAX_ATTEMPTS) { await new Promise((resolve) => setTimeout(resolve, retryDelaySeconds(response.headers.get("Retry-After"), attempt) * 1000)); continue; }
        throw new SafeRxProblemDetailsError(response.status, (parsed ?? { status: response.status, title: "REQUEST_FAILED" }) as JsonObject, requestId);
      } catch (error) { if (error instanceof SafeRxProblemDetailsError) throw error; if (attempt + 1 >= MAX_ATTEMPTS) throw new SafeRxProblemDetailsError(503, { status: 503, title: "UPSTREAM_UNAVAILABLE", safe_to_retry: true }, requestId); await new Promise((resolve) => setTimeout(resolve, Math.min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * 2 ** attempt) * 1000)); }
    }
    throw new Error("retry loop exhausted");
  }
}
