// This file was auto-generated by Fern from our API Definition.

import { DevelopersClient } from "./api/resources/developers/client/Client.js";
import { DrugSafetyClient } from "./api/resources/drugSafety/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace SafeRxClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SafeRxClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SafeRxClient.Options>;
    protected _drugSafety: DrugSafetyClient | undefined;
    protected _developers: DevelopersClient | undefined;

    constructor(options: SafeRxClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get drugSafety(): DrugSafetyClient {
        return (this._drugSafety ??= new DrugSafetyClient(this._options));
    }

    public get developers(): DevelopersClient {
        return (this._developers ??= new DevelopersClient(this._options));
    }
}
