// This file was auto-generated by Fern from our API Definition.

export const SafeRxEnvironment = {
    Production: "https://saferx.online",
} as const;

export type SafeRxEnvironment = typeof SafeRxEnvironment.Production;
