# AUTO-GENERATED by tools/generate_enterprise_sdks.py
"""MIS Enterprise Python SDK release candidate.

Generated operation metadata is sourced from ``api/openapi/enterprise-v1.yaml``.
This client does not authenticate from client attribution labels; those labels
are bounded, non-authoritative usage dimensions only.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import secrets
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlsplit
from urllib.request import Request, urlopen


MAX_ATTEMPTS = 3
RETRY_BACKOFF_BASE_SECONDS = 0.1
RETRY_BACKOFF_MAX_SECONDS = 2.0
CLIENT_KIND = "python_sdk"
SDK_LANGUAGE = "python"
SDK_VERSION = "0.1.0-rc.1"


@dataclass(frozen=True)
class Operation:
    operation_id: str
    method: str
    path: str
    route_class: str
    response_profile: str
    quota_metric: str
    idempotency_required: bool


OPERATIONS = {
    'enterprise_allergy_families': Operation('enterprise_allergy_families', 'GET', '/allergies/families', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_allergy_resolve': Operation('enterprise_allergy_resolve', 'POST', '/allergies/resolve', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_allergy_substances': Operation('enterprise_allergy_substances', 'GET', '/allergies/substances', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_capabilities': Operation('enterprise_capabilities', 'GET', '/capabilities', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_erx_safety_check': Operation('enterprise_erx_safety_check', 'POST', '/erx/safety-checks', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', True),
    'enterprise_ocr_prescription_create': Operation('enterprise_ocr_prescription_create', 'POST', '/ocr/prescriptions', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', True),
    'enterprise_ocr_prescription_events': Operation('enterprise_ocr_prescription_events', 'GET', '/ocr/prescriptions/{prescription_id}/events', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_ocr_prescription_read': Operation('enterprise_ocr_prescription_read', 'GET', '/ocr/prescriptions/{prescription_id}', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_ocr_prescription_resolve': Operation('enterprise_ocr_prescription_resolve', 'POST', '/ocr/prescriptions/{prescription_id}/medications/resolve', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_ocr_prescription_review': Operation('enterprise_ocr_prescription_review', 'POST', '/ocr/prescriptions/{prescription_id}/review', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_ocr_prescription_safety': Operation('enterprise_ocr_prescription_safety', 'POST', '/ocr/prescriptions/{prescription_id}/safety-checks', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_registry_autocomplete': Operation('enterprise_registry_autocomplete', 'GET', '/registry/suggest', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_registry_ingredients': Operation('enterprise_registry_ingredients', 'GET', '/registry/ingredients', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_registry_product_detail': Operation('enterprise_registry_product_detail', 'GET', '/registry/products/{sfrx_id}', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_registry_resolve': Operation('enterprise_registry_resolve', 'POST', '/registry/resolve', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_registry_search': Operation('enterprise_registry_search', 'GET', '/registry/search', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_safety_capabilities': Operation('enterprise_safety_capabilities', 'GET', '/safety/capabilities', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_safety_check': Operation('enterprise_safety_check', 'POST', '/safety/checks', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', True),
    'enterprise_safety_check_batch': Operation('enterprise_safety_check_batch', 'POST', '/safety/check-batches', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', True),
    'enterprise_safety_check_read': Operation('enterprise_safety_check_read', 'GET', '/safety/checks/{check_id}', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
    'enterprise_status': Operation('enterprise_status', 'GET', '/status', 'enterprise_unknown', 'rp_enterprise_default', 'enterprise_request', False),
}


class SafeRxProblemDetailsError(RuntimeError):
    """RFC 9457 error with bounded response metadata and safe retry advice."""

    def __init__(self, status: int, problem: dict[str, Any], request_id: str | None = None):
        self.status = status
        self.problem = problem
        self.request_id = request_id or problem.get("request_id")
        self.retry_after = problem.get("retry_after")
        super().__init__(problem.get("detail") or problem.get("title") or "Enterprise request failed")


def canonical_query(query: dict[str, Any] | None) -> str:
    if not query:
        return ""
    pairs: list[tuple[str, str]] = []
    for key, value in query.items():
        values = value if isinstance(value, (list, tuple)) else [value]
        pairs.extend((str(key), str(item)) for item in values)
    return "&".join(
        f"{quote(key, safe='-._~')}={quote(value, safe='-._~')}"
        for key, value in sorted(pairs)
    )


def canonical_request(method: str, path: str, query: str, body_sha256: str, timestamp: str, nonce: str) -> str:
    return "\n".join((method.upper(), quote(path, safe="/-._~"), query, body_sha256, timestamp, nonce))


def sign_request(api_key: str, method: str, path: str, query: str, body: bytes, timestamp: str, nonce: str) -> str:
    body_hash = hashlib.sha256(body).hexdigest()
    payload = canonical_request(method, path, query, body_hash, timestamp, nonce)
    digest = hmac.new(api_key.encode("utf-8"), payload.encode("utf-8"), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


class SafeRxClient:
    def __init__(self, base_url: str, api_key: str, *, client_name: str = "saferx-pharma", timeout: float = 30.0):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.client_name = client_name
        self.timeout = timeout

    def request(
        self,
        operation_id: str,
        *,
        query: dict[str, Any] | None = None,
        body: Any = None,
        path_params: dict[str, Any] | None = None,
        idempotency_key: str | None = None,
    ) -> Any:
        operation = OPERATIONS[operation_id]
        path = operation.path
        for name, value in (path_params or {}).items():
            path = path.replace("{" + name + "}", quote(str(value), safe="-._~"))
        body_bytes = b"" if body is None else json.dumps(body, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode()
        canonical_q = canonical_query(query)
        target = f"{self.base_url}{path}{('?' + canonical_q) if canonical_q else ''}"
        request_id = secrets.token_hex(16)
        timestamp = datetime.now(UTC).isoformat(timespec="seconds")
        nonce = secrets.token_urlsafe(24)
        signing_path = urlsplit(self.base_url).path.rstrip("/") + path
        headers = {
            "Accept": "application/json",
            "X-SafeRx-API-Key": self.api_key,
            "X-SafeRx-Timestamp": timestamp,
            "X-SafeRx-Nonce": nonce,
            "X-SafeRx-Signature": sign_request(self.api_key, operation.method, signing_path, canonical_q, body_bytes, timestamp, nonce),
            "X-Request-ID": request_id,
            "X-SafeRx-Client-Kind": CLIENT_KIND,
            "X-SafeRx-Client-Name": self.client_name,
            "X-SafeRx-Client-Version": SDK_VERSION,
            "X-SafeRx-SDK-Language": SDK_LANGUAGE,
            "X-SafeRx-SDK-Version": SDK_VERSION,
        }
        if body is not None:
            headers["Content-Type"] = "application/json"
        if operation.idempotency_required and not idempotency_key:
            raise ValueError(f"{operation_id} requires idempotency_key")
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        request = Request(target, data=body_bytes or None, headers=headers, method=operation.method)
        for attempt in range(MAX_ATTEMPTS):
            try:
                with urlopen(request, timeout=self.timeout) as response:
                    raw = response.read()
                    return json.loads(raw) if raw else None
            except HTTPError as error:
                raw = error.read()
                problem = json.loads(raw) if raw else {"status": error.code, "title": "REQUEST_FAILED"}
                if error.code in {502, 503, 504} and attempt + 1 < MAX_ATTEMPTS:
                    time.sleep(min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * (2**attempt)))
                    continue
                raise SafeRxProblemDetailsError(error.code, problem, request_id) from error
            except (TimeoutError, URLError) as error:
                if attempt + 1 < MAX_ATTEMPTS:
                    time.sleep(min(RETRY_BACKOFF_MAX_SECONDS, RETRY_BACKOFF_BASE_SECONDS * (2**attempt)))
                    continue
                raise SafeRxProblemDetailsError(503, {"status": 503, "title": "UPSTREAM_UNAVAILABLE", "safe_to_retry": True}, request_id) from error
        raise AssertionError("retry loop exhausted")


def _operation_method(operation: str):
    def call(self: SafeRxClient, **kwargs: Any) -> Any:
        return self.request(operation, **kwargs)
    call.__name__ = operation
    return call


for _operation_id in OPERATIONS:
    setattr(SafeRxClient, _operation_id, _operation_method(_operation_id))
